# Preliminary analysis
This notebook opens the file named 'responses_scrubbed_tagged.csv', which is created by running the 'free_text_tagging.ipynb' notebook, and does an automatic preliminary analysis of some statistics in the responses therein.

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display, Markdown, Latex
df = pd.read_csv('responses_complete.csv', index_col=None, parse_dates=['date'])

#don't truncate results
pd.set_option('display.max_rows', None)

## Number of respondents from each neighborhood
Gives us a sense of who responded.

In [2]:
# absolute values
df['neighborhood'].value_counts()

Harmon                 166
Upper Village          118
Old Post Road North     77
Mount Airy              67
Sunset Park             48
Albany Post Road        31
Half Moon Bay           21
Quaker Ridge            11
Cortlandt               10
Ossining                 1
Name: neighborhood, dtype: int64

In [3]:
# as percent
percent = df['neighborhood'].value_counts(normalize=True).mul(100).round(1).astype(str) + '%'
percent

Harmon                 30.2%
Upper Village          21.5%
Old Post Road North    14.0%
Mount Airy             12.2%
Sunset Park             8.7%
Albany Post Road        5.6%
Half Moon Bay           3.8%
Quaker Ridge            2.0%
Cortlandt               1.8%
Ossining                0.2%
Name: neighborhood, dtype: object

## Number of respondents from each demographic
Gives us a sense of who responded.

In [4]:
# absolute values
df['demographic'].value_counts()

Adult with school kid       232
Adult without school kid    174
Senior                      140
College kid                   5
Middle School kid             3
High School kid               3
Name: demographic, dtype: int64

In [5]:
# as percent
df['demographic'].value_counts(normalize=True).mul(100).round(0).astype(str) + '%'

Adult with school kid       42.0%
Adult without school kid    31.0%
Senior                      25.0%
College kid                  1.0%
Middle School kid            1.0%
High School kid              1.0%
Name: demographic, dtype: object

## Percent respondents of each demographic from each neighborhood
Each column adds up to 100%.

In [6]:
df2 = df.groupby(['demographic', 'neighborhood']).size().unstack(fill_value=0).apply(lambda x: 100 * x / x.sum()) #.astype(int)
df2.round(0).astype(int).astype(str) + '%' # round to int, the slap on percent sign

neighborhood,Albany Post Road,Cortlandt,Half Moon Bay,Harmon,Mount Airy,Old Post Road North,Ossining,Quaker Ridge,Sunset Park,Upper Village
demographic,,,,,,,,,,
Adult with school kid,19%,40%,14%,40%,55%,45%,0%,55%,48%,43%
Adult without school kid,29%,40%,43%,27%,24%,33%,100%,27%,38%,33%
College kid,0%,0%,0%,2%,0%,1%,0%,0%,2%,0%
High School kid,0%,0%,0%,1%,1%,0%,0%,0%,0%,0%
Middle School kid,0%,0%,0%,1%,0%,1%,0%,0%,0%,1%
Senior,52%,20%,43%,30%,19%,20%,0%,18%,12%,23%

## Analyze questions with only one answer option allowed

In [7]:
# a function that calculates how many responses were given in a specific column
def get_num_respondents(field, df):
    # get the number of responses in this field
    num_respondents = df[pd.notnull(df[field])].shape[0]
    return num_respondents

def get_breakdown(field, breakdown_field, percent=True):
    # get the number of respondents to this field
    num_respondents = get_num_respondents(field, df)

    # get the overall stats of the values in the field of interest
    df2 = df[field].value_counts()
    if percent:
        df2 = df2.apply(lambda x: int(100 * x / num_respondents))
    
    # label the column nicely 
    df2 = df2.to_frame()
    df2.columns = ['overall'] #name this 'overall', since it is not broken down

    # get the various values given in the field we want to break down the target field by
    breakdowns = df[breakdown_field].value_counts().items()

    # now break down the field by each of the values in the breakdown field
    for breakdown, value in breakdowns:        
        # get the number of responses by respondents matching this breakdown category
        df3 = df[df[breakdown_field] == breakdown][field].value_counts()
        
        # convert to percentage, if desired
        if percent:
            # get the number of respondents to this field
            num_respondents_column = get_num_respondents(field, df[df[breakdown_field] == breakdown][field].to_frame())
            
            df3 = df3.apply(lambda x: int(100 * x / num_respondents_column))

        # label the column nicely before we merge it into the other dataframe
        df3 = df3.to_frame() # convert to dataframe
        df3.columns = [breakdown]
        

        # join these two dataframes together
        df2 = df2.join(df3, how='outer')

    # add percent signs if calculating percentages
    if percent:
        df2 = df2.round(0).fillna(0).astype(int).astype(str) + '%'
        
    # sort by index names to be consistent
    #df2 = df2.sort_values(by='overall', ascending=False)
    df2 = df2.sort_index()

    return df2

# fields of interest
fields = [ 'child_bus_freq', 'child_walk_freq', 'child_driven_freq', 'child_drive_freq', 'child_bike_freq', 'walk_freq', 'bike_freq', 'bikes_on_sidewalk', 'self_jog_frequency', 'commutes', 'child_self_school', 'child_self_bus_freq', 'child_self_bike_freq', 'child_self_driven_freq', 'child_self_drive_freq', 'child_self_walk_freq', 'child_self_commutes', 'child_self_has_children', 'commuter_type', 'commuter_walk_to_station_freq', 'commuter_bike_to_station_freq', 'commuter_drive_to_station_freq', 'commuter_carpool_to_station_freq', 'commuter_driven_to_station_freq', 'commuter_bus_to_station_freq', 'drivers_are_safe', 'bicyclists_are_safe', 'contact_interest' ]
# not included: ['child_drive_reason', 'child_no_walk_reason', 'child_no_bike_reason', 'commuter_distance', 'no_walk_reason', 'no_bike_reason', 'drive_reason' ]

# add in the tagging fields, if desired
fields.extend([ 'problem_tags_129', 'problem_tags_aggressive driving', 'problem_tags_benedict', 'problem_tags_bushes on sidewalk', 'problem_tags_cet', 'problem_tags_cleveland', 'problem_tags_cpa', 'problem_tags_crossing guard', 'problem_tags_croton commons', 'problem_tags_cyclists breaking rules', 'problem_tags_driver awareness', 'problem_tags_dummy light', 'problem_tags_five corners', 'problem_tags_gottwald circle', 'problem_tags_grand', 'problem_tags_hmb trail', 'problem_tags_maple', 'problem_tags_missing crosswalks', 'problem_tags_missing sidewalks', 'problem_tags_morningside', 'problem_tags_mt airy', 'problem_tags_municipal place', 'problem_tags_n riverside', 'problem_tags_narrow roads', 'problem_tags_olcott', 'problem_tags_old post n', 'problem_tags_old post s', 'problem_tags_on-street parking', 'problem_tags_poor lighting', 'problem_tags_road surface', 'problem_tags_s riverside', 'problem_tags_shoprite', 'problem_tags_sidewalk condition', 'problem_tags_speeding', 'problem_tags_truesdale', 'problem_tags_van wyck', 'schools_CET', 'schools_CHHS', 'schools_Homeschooled', 'schools_PVC', 'suggestion_tags_better lighting', 'suggestion_tags_bike lanes', 'suggestion_tags_bike racks', 'suggestion_tags_dedicated pedestrian walk signals', 'suggestion_tags_educate cyclists', 'suggestion_tags_educate pedestrians', 'suggestion_tags_enforce crosswalks', 'suggestion_tags_enforce speed', 'suggestion_tags_enforce trimming of bushes', 'suggestion_tags_improve route 9 access', 'suggestion_tags_maintain crosswalks', 'suggestion_tags_maintain sidewalks', 'suggestion_tags_more crosswalks', 'suggestion_tags_more sidewalks', 'suggestion_tags_more signs', 'suggestion_tags_more stop signs', 'suggestion_tags_more traffic lights', 'suggestion_tags_no bike lanes', 'suggestion_tags_outlaw cycling', 'suggestion_tags_parking on one side only', 'suggestion_tags_reduce on-street parking', 'suggestion_tags_reduce speed', 'suggestion_tags_sidewalk on mt airy s', 'suggestion_tags_speed bumps', 'suggestion_tags_speed cameras', 'suggestion_tags_speed indicator signs', 'suggestion_tags_traffic calming' ])

# iterate through every field of interest
for field in fields:
    
    # different fields by which we will break down each column in the data set... add as many as we think are interesting
    breakdowns = {
        'demographic': get_breakdown(field, 'demographic', percent=True),
        'neighborhood': get_breakdown(field, 'neighborhood', percent=True),
        'commuter_type': get_breakdown(field, 'commuter_type', percent=True),
        'bike_freq': get_breakdown(field, 'bike_freq', percent=True),
        'walk_freq': get_breakdown(field, 'walk_freq', percent=True)
    }
    
    # print out results overall in general on average
    display(Markdown('## *{}* (each column adds up to 100%):'.format(field, get_num_respondents(field, df)).title()))

    # break down the results by each of the breakdown fields
    for breakdown_field, results in breakdowns.items():        
        display(Markdown('### {} broken down by {}:'.format(field, breakdown_field)))
        display(results)

## *Child_Bus_Freq* (Each Column Adds Up To 100%):

### child_bus_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",49%,49%,0%,0%,0%,0%,0%
Once every few days,3%,3%,0%,0%,0%,0%,0%
Once in a while,6%,6%,0%,0%,0%,0%,0%
Rarely or never,40%,40%,0%,0%,0%,0%,0%

### child_bus_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",49%,40%,47%,52%,64%,47%,50%,33%,33%,75%,0%
Once every few days,3%,7%,0%,5%,2%,4%,0%,0%,0%,0%,0%
Once in a while,6%,10%,6%,5%,8%,0%,0%,0%,0%,0%,0%
Rarely or never,40%,41%,45%,35%,24%,47%,50%,66%,66%,25%,0%

### child_bus_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",49%,51%,41%,0%,100%,0%,100%
Once every few days,3%,5%,4%,0%,0%,0%,0%
Once in a while,6%,7%,6%,0%,0%,0%,0%
Rarely or never,40%,37%,47%,100%,0%,100%,0%

### child_bus_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",49%,50%,47%,46%,50%
Once every few days,3%,1%,6%,10%,0%
Once in a while,6%,4%,9%,7%,12%
Rarely or never,40%,44%,36%,35%,37%

### child_bus_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",49%,49%,47%,49%,56%
Once every few days,3%,4%,6%,1%,0%
Once in a while,6%,6%,3%,8%,12%
Rarely or never,40%,39%,42%,40%,31%

## *Child_Walk_Freq* (Each Column Adds Up To 100%):

### child_walk_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",25%,25%,0%,0%,0%,0%,0%
Once every few days,7%,7%,0%,0%,0%,0%,0%
Once in a while,18%,18%,0%,0%,0%,0%,0%
Rarely or never - for other reasons,25%,25%,0%,0%,0%,0%,0%
Rarely or never - my children are too young,23%,23%,0%,0%,0%,0%,0%

### child_walk_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",25%,25%,40%,23%,5%,47%,0%,0%,0%,0%,0%
Once every few days,7%,8%,10%,8%,2%,0%,33%,0%,0%,0%,0%
Once in a while,18%,25%,10%,20%,16%,17%,0%,66%,16%,0%,0%
Rarely or never - for other reasons,25%,14%,8%,29%,67%,8%,66%,0%,33%,50%,0%
Rarely or never - my children are too young,23%,25%,30%,17%,8%,26%,0%,33%,50%,50%,0%

### child_walk_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",25%,31%,25%,100%,0%,100%,0%
Once every few days,7%,10%,6%,0%,0%,0%,0%
Once in a while,18%,12%,20%,0%,0%,0%,0%
Rarely or never - for other reasons,25%,14%,30%,0%,100%,0%,100%
Rarely or never - my children are too young,23%,29%,16%,0%,0%,0%,0%

### child_walk_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",25%,23%,27%,28%,31%
Once every few days,7%,8%,1%,17%,0%
Once in a while,18%,16%,24%,7%,25%
Rarely or never - for other reasons,25%,25%,32%,14%,18%
Rarely or never - my children are too young,23%,26%,13%,32%,25%

### child_walk_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",25%,34%,20%,25%,12%
Once every few days,7%,2%,10%,10%,0%
Once in a while,18%,15%,26%,11%,12%
Rarely or never - for other reasons,25%,20%,21%,23%,75%
Rarely or never - my children are too young,23%,27%,20%,28%,0%

## *Child_Driven_Freq* (Each Column Adds Up To 100%):

### child_driven_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",28%,28%,0%,0%,0%,0%,0%
Once every few days,15%,15%,0%,0%,0%,0%,0%
Once in a while,20%,20%,0%,0%,0%,0%,0%
Rarely or never,35%,35%,0%,0%,0%,0%,0%

### child_driven_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",28%,31%,20%,35%,29%,26%,16%,66%,33%,25%,0%
Once every few days,15%,10%,14%,14%,13%,30%,33%,0%,50%,0%,0%
Once in a while,20%,22%,22%,23%,24%,4%,16%,0%,0%,75%,0%
Rarely or never,35%,35%,42%,26%,32%,39%,33%,33%,16%,0%,0%

### child_driven_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",28%,24%,33%,0%,0%,0%,0%
Once every few days,15%,13%,15%,0%,50%,100%,0%
Once in a while,20%,23%,20%,0%,0%,0%,100%
Rarely or never,35%,37%,30%,100%,50%,0%,0%

### child_driven_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",28%,28%,32%,21%,25%
Once every few days,15%,13%,18%,17%,18%
Once in a while,20%,20%,19%,28%,12%
Rarely or never,35%,36%,29%,32%,43%

### child_driven_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",28%,21%,31%,30%,37%
Once every few days,15%,16%,14%,16%,12%
Once in a while,20%,19%,26%,15%,18%
Rarely or never,35%,42%,27%,37%,31%

## *Child_Drive_Freq* (Each Column Adds Up To 100%):

### child_drive_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",2%,2%,0%,0%,0%,0%,0%
Once every few days,3%,3%,0%,0%,0%,0%,0%
Once in a while,1%,1%,0%,0%,0%,0%,0%
Rarely or never - for other reasons,18%,18%,0%,0%,0%,0%,0%
Rarely or never - my children are too young,74%,74%,0%,0%,0%,0%,0%

### child_drive_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",2%,1%,0%,3%,5%,0%,0%,0%,16%,0%,0%
Once every few days,3%,1%,0%,3%,5%,0%,33%,0%,0%,0%,0%
Once in a while,1%,1%,2%,3%,2%,0%,0%,0%,0%,0%,0%
Rarely or never - for other reasons,18%,20%,20%,15%,8%,26%,16%,66%,16%,0%,0%
Rarely or never - my children are too young,74%,74%,77%,75%,78%,73%,50%,33%,66%,100%,0%

### child_drive_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",2%,0%,2%,0%,0%,0%,0%
Once every few days,3%,1%,6%,0%,0%,0%,0%
Once in a while,1%,0%,4%,0%,0%,0%,0%
Rarely or never - for other reasons,18%,10%,26%,0%,100%,0%,0%
Rarely or never - my children are too young,74%,86%,59%,100%,0%,100%,100%

### child_drive_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",2%,0%,4%,3%,0%
Once every few days,3%,4%,3%,0%,0%
Once in a while,1%,1%,3%,0%,0%
Rarely or never - for other reasons,18%,18%,21%,10%,18%
Rarely or never - my children are too young,74%,75%,67%,85%,81%

### child_drive_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",2%,0%,2%,5%,0%
Once every few days,3%,2%,2%,5%,0%
Once in a while,1%,2%,1%,0%,6%
Rarely or never - for other reasons,18%,19%,21%,10%,25%
Rarely or never - my children are too young,74%,75%,71%,79%,68%

## *Child_Bike_Freq* (Each Column Adds Up To 100%):

### child_bike_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",0%,0%,0%,0%,0%,0%,0%
Once every few days,0%,0%,0%,0%,0%,0%,0%
Once in a while,8%,8%,0%,0%,0%,0%,0%
Rarely or never - for other reasons,56%,56%,0%,0%,0%,0%,0%
Rarely or never - my children are too young,33%,33%,0%,0%,0%,0%,0%

### child_bike_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",0%,1%,0%,0%,0%,0%,0%,0%,0%,0%,0%
Once every few days,0%,0%,2%,0%,0%,4%,0%,0%,0%,0%,0%
Once in a while,8%,10%,8%,8%,2%,17%,0%,0%,0%,0%,0%
Rarely or never - for other reasons,56%,49%,42%,64%,81%,43%,100%,100%,50%,50%,0%
Rarely or never - my children are too young,33%,38%,46%,26%,16%,34%,0%,0%,50%,50%,0%

### child_bike_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",0%,0%,1%,0%,0%,0%,0%
Once every few days,0%,1%,1%,0%,0%,0%,0%
Once in a while,8%,10%,7%,0%,0%,0%,0%
Rarely or never - for other reasons,56%,48%,66%,100%,100%,100%,100%
Rarely or never - my children are too young,33%,41%,23%,0%,0%,0%,0%

### child_bike_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",0%,0%,0%,0%,0%
Once every few days,0%,0%,0%,3%,6%
Once in a while,8%,3%,13%,14%,18%
Rarely or never - for other reasons,56%,59%,64%,35%,50%
Rarely or never - my children are too young,33%,36%,22%,46%,25%

### child_bike_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",0%,0%,1%,0%,0%
Once every few days,0%,1%,0%,1%,0%
Once in a while,8%,13%,7%,5%,0%
Rarely or never - for other reasons,56%,52%,52%,57%,93%
Rarely or never - my children are too young,33%,31%,39%,35%,6%

## *Walk_Freq* (Each Column Adds Up To 100%):

### walk_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",34%,31%,36%,38%,0%,0%,0%
Once every few days,32%,35%,34%,25%,40%,0%,0%
Once in a while,23%,25%,20%,24%,40%,0%,0%
Rarely or never,8%,6%,8%,11%,20%,0%,0%

### walk_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",34%,43%,38%,21%,18%,37%,22%,60%,9%,33%,0%
Once every few days,32%,32%,35%,39%,28%,26%,29%,35%,36%,33%,0%
Once in a while,23%,18%,19%,27%,34%,26%,38%,5%,36%,33%,100%
Rarely or never,8%,5%,7%,12%,18%,8%,9%,0%,18%,0%,0%

### walk_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",34%,30%,31%,75%,33%,0%,0%
Once every few days,32%,36%,37%,25%,33%,100%,50%
Once in a while,23%,27%,20%,0%,0%,0%,50%
Rarely or never,8%,6%,10%,0%,33%,0%,0%

### walk_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",34%,27%,40%,43%,58%
Once every few days,32%,32%,34%,37%,16%
Once in a while,23%,26%,22%,17%,19%
Rarely or never,8%,13%,1%,1%,6%

### walk_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",34%,100%,0%,0%,0%
Once every few days,32%,0%,100%,0%,0%
Once in a while,23%,0%,0%,100%,0%
Rarely or never,8%,0%,0%,0%,100%

## *Bike_Freq* (Each Column Adds Up To 100%):

### bike_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",5%,6%,5%,4%,20%,0%,0%
Once every few days,13%,12%,15%,12%,20%,0%,0%
Once in a while,22%,26%,24%,12%,40%,0%,0%
Rarely or never,58%,54%,55%,70%,20%,0%,0%

### bike_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",5%,5%,5%,5%,6%,8%,3%,10%,9%,0%,0%
Once every few days,13%,14%,14%,12%,9%,17%,6%,30%,0%,22%,0%
Once in a while,22%,24%,20%,17%,24%,24%,20%,15%,27%,11%,100%
Rarely or never,58%,55%,60%,64%,60%,48%,70%,45%,63%,66%,0%

### bike_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",5%,10%,2%,0%,66%,0%,0%
Once every few days,13%,17%,7%,0%,0%,0%,0%
Once in a while,22%,25%,27%,25%,0%,0%,0%
Rarely or never,58%,47%,62%,75%,33%,100%,100%

### bike_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",5%,0%,0%,0%,100%
Once every few days,13%,0%,0%,100%,0%
Once in a while,22%,0%,100%,0%,0%
Rarely or never,58%,100%,0%,0%,0%

### bike_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",5%,9%,2%,4%,4%
Once every few days,13%,16%,14%,9%,2%
Once in a while,22%,26%,23%,21%,4%
Rarely or never,58%,47%,58%,64%,89%

## *Bikes_On_Sidewalk* (Each Column Adds Up To 100%):

### bikes_on_sidewalk by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
No - I don't bicycle,48%,40%,47%,63%,0%,0%,0%
No - I only bicycle on the road,28%,29%,29%,26%,60%,0%,0%
Yes,22%,30%,22%,10%,40%,0%,0%

### bikes_on_sidewalk by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
No - I don't bicycle,48%,46%,53%,50%,46%,37%,60%,40%,36%,55%,0%
No - I only bicycle on the road,28%,28%,20%,25%,40%,37%,16%,45%,54%,33%,0%
Yes,22%,25%,25%,25%,12%,24%,23%,15%,9%,11%,100%

### bikes_on_sidewalk by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
No - I don't bicycle,48%,35%,53%,50%,0%,0%,100%
No - I only bicycle on the road,28%,31%,23%,25%,66%,100%,0%
Yes,22%,33%,23%,25%,33%,0%,0%

### bikes_on_sidewalk by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
No - I don't bicycle,48%,80%,1%,0%,0%
No - I only bicycle on the road,28%,12%,49%,56%,60%
Yes,22%,6%,49%,43%,40%

### bikes_on_sidewalk by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
No - I don't bicycle,48%,40%,46%,49%,82%
No - I only bicycle on the road,28%,29%,29%,33%,14%
Yes,22%,30%,24%,17%,2%

## *Self_Jog_Frequency* (Each Column Adds Up To 100%):

### self_jog_frequency by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",4%,5%,5%,2%,20%,0%,0%
Once every few days,12%,19%,10%,4%,0%,0%,0%
Once in a while,16%,25%,15%,2%,20%,0%,0%
Rarely or never,65%,50%,67%,89%,60%,0%,0%

### self_jog_frequency by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",4%,7%,4%,4%,3%,4%,0%,0%,9%,11%,0%
Once every few days,12%,12%,10%,13%,10%,31%,10%,5%,9%,0%,0%
Once in a while,16%,14%,20%,20%,18%,20%,10%,5%,9%,11%,0%
Rarely or never,65%,65%,64%,62%,68%,44%,80%,90%,72%,77%,100%

### self_jog_frequency by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",4%,5%,6%,0%,33%,0%,0%
Once every few days,12%,16%,11%,0%,33%,0%,0%
Once in a while,16%,23%,18%,0%,0%,100%,50%
Rarely or never,65%,54%,62%,100%,33%,0%,50%

### self_jog_frequency by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",4%,3%,8%,2%,9%
Once every few days,12%,9%,12%,21%,22%
Once in a while,16%,14%,24%,15%,9%
Rarely or never,65%,72%,54%,60%,58%

### self_jog_frequency by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",4%,9%,2%,3%,0%
Once every few days,12%,15%,15%,5%,6%
Once in a while,16%,13%,19%,18%,12%
Rarely or never,65%,61%,61%,72%,80%

## *Commutes* (Each Column Adds Up To 100%):

### commutes by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
No,37%,22%,20%,82%,20%,0%,0%
Yes,0%,1%,1%,0%,0%,0%,0%
Yes - I commute daily,49%,63%,64%,10%,80%,0%,0%
Yes - I occasionally commute,11%,13%,13%,7%,0%,0%,0%

### commutes by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
No,37%,38%,34%,35%,37%,28%,46%,65%,27%,44%,0%
Yes,0%,1%,0%,2%,0%,0%,0%,0%,0%,0%,0%
Yes - I commute daily,49%,46%,51%,49%,48%,64%,43%,35%,63%,55%,100%
Yes - I occasionally commute,11%,13%,14%,12%,13%,6%,10%,0%,9%,0%,0%

### commutes by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
No,37%,0%,0%,0%,0%,0%,0%
Yes,0%,2%,0%,0%,0%,0%,0%
Yes - I commute daily,49%,74%,84%,75%,100%,100%,100%
Yes - I occasionally commute,11%,22%,15%,25%,0%,0%,0%

### commutes by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
No,37%,41%,26%,39%,25%
Yes,0%,0%,0%,2%,6%
Yes - I commute daily,49%,47%,59%,46%,48%
Yes - I occasionally commute,11%,10%,12%,11%,19%

### commutes by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
No,37%,43%,29%,36%,42%
Yes,0%,2%,0%,0%,0%
Yes - I commute daily,49%,42%,55%,54%,48%
Yes - I occasionally commute,11%,12%,15%,8%,8%

## *Child_Self_School* (Each Column Adds Up To 100%):

### child_self_school by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
CHHS,50%,0%,0%,0%,0%,0%,100%
PVC,33%,0%,0%,0%,0%,66%,0%
Windward,16%,0%,0%,0%,0%,33%,0%

### child_self_school by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
CHHS,50%,66%,0%,0%,100%,0%,0%,0%,0%,0%,0%
PVC,33%,33%,100%,0%,0%,0%,0%,0%,0%,0%,0%
Windward,16%,0%,0%,100%,0%,0%,0%,0%,0%,0%,0%

### child_self_school by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
CHHS,50%,0%,100%,0%,0%,0%,0%
PVC,33%,0%,0%,0%,0%,0%,0%
Windward,16%,0%,0%,0%,0%,100%,0%

### child_self_school by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
CHHS,50%,0%,0%,0%,0%
PVC,33%,0%,0%,0%,0%
Windward,16%,0%,0%,0%,0%

### child_self_school by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
CHHS,50%,0%,0%,0%,0%
PVC,33%,0%,0%,0%,0%
Windward,16%,0%,0%,0%,0%

## *Child_Self_Bus_Freq* (Each Column Adds Up To 100%):

### child_self_bus_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",33%,0%,0%,0%,0%,33%,33%
Once every few days,16%,0%,0%,0%,0%,33%,0%
Rarely or never,50%,0%,0%,0%,0%,33%,66%

### child_self_bus_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",33%,0%,0%,100%,100%,0%,0%,0%,0%,0%,0%
Once every few days,16%,33%,0%,0%,0%,0%,0%,0%,0%,0%,0%
Rarely or never,50%,66%,100%,0%,0%,0%,0%,0%,0%,0%,0%

### child_self_bus_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",33%,0%,0%,0%,0%,100%,0%
Once every few days,16%,0%,0%,0%,0%,0%,0%
Rarely or never,50%,0%,100%,0%,0%,0%,0%

### child_self_bus_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",33%,0%,0%,0%,0%
Once every few days,16%,0%,0%,0%,0%
Rarely or never,50%,0%,0%,0%,0%

### child_self_bus_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",33%,0%,0%,0%,0%
Once every few days,16%,0%,0%,0%,0%
Rarely or never,50%,0%,0%,0%,0%

## *Child_Self_Bike_Freq* (Each Column Adds Up To 100%):

### child_self_bike_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
Once every few days,16%,0%,0%,0%,0%,33%,0%
Once in a while,16%,0%,0%,0%,0%,33%,0%
Rarely or never,66%,0%,0%,0%,0%,33%,100%

### child_self_bike_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
Once every few days,16%,0%,100%,0%,0%,0%,0%,0%,0%,0%,0%
Once in a while,16%,33%,0%,0%,0%,0%,0%,0%,0%,0%,0%
Rarely or never,66%,66%,0%,100%,100%,0%,0%,0%,0%,0%,0%

### child_self_bike_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
Once every few days,16%,0%,0%,0%,0%,0%,0%
Once in a while,16%,0%,0%,0%,0%,0%,0%
Rarely or never,66%,0%,100%,0%,0%,100%,0%

### child_self_bike_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
Once every few days,16%,0%,0%,0%,0%
Once in a while,16%,0%,0%,0%,0%
Rarely or never,66%,0%,0%,0%,0%

### child_self_bike_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
Once every few days,16%,0%,0%,0%,0%
Once in a while,16%,0%,0%,0%,0%
Rarely or never,66%,0%,0%,0%,0%

## *Child_Self_Driven_Freq* (Each Column Adds Up To 100%):

### child_self_driven_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",16%,0%,0%,0%,0%,33%,0%
Once in a while,33%,0%,0%,0%,0%,66%,0%
Rarely or never,50%,0%,0%,0%,0%,0%,100%

### child_self_driven_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",16%,33%,0%,0%,0%,0%,0%,0%,0%,0%,0%
Once in a while,33%,0%,100%,100%,0%,0%,0%,0%,0%,0%,0%
Rarely or never,50%,66%,0%,0%,100%,0%,0%,0%,0%,0%,0%

### child_self_driven_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",16%,0%,0%,0%,0%,0%,0%
Once in a while,33%,0%,0%,0%,0%,100%,0%
Rarely or never,50%,0%,100%,0%,0%,0%,0%

### child_self_driven_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",16%,0%,0%,0%,0%
Once in a while,33%,0%,0%,0%,0%
Rarely or never,50%,0%,0%,0%,0%

### child_self_driven_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",16%,0%,0%,0%,0%
Once in a while,33%,0%,0%,0%,0%
Rarely or never,50%,0%,0%,0%,0%

## *Child_Self_Drive_Freq* (Each Column Adds Up To 100%):

### child_self_drive_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",16%,0%,0%,0%,0%,0%,33%
Rarely or never - I'm too young,50%,0%,0%,0%,0%,66%,33%
Rarely or never - for other reasons,33%,0%,0%,0%,0%,33%,33%

### child_self_drive_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",16%,33%,0%,0%,0%,0%,0%,0%,0%,0%,0%
Rarely or never - I'm too young,50%,33%,0%,100%,100%,0%,0%,0%,0%,0%,0%
Rarely or never - for other reasons,33%,33%,100%,0%,0%,0%,0%,0%,0%,0%,0%

### child_self_drive_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",16%,0%,100%,0%,0%,0%,0%
Rarely or never - I'm too young,50%,0%,0%,0%,0%,100%,0%
Rarely or never - for other reasons,33%,0%,0%,0%,0%,0%,0%

### child_self_drive_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",16%,0%,0%,0%,0%
Rarely or never - I'm too young,50%,0%,0%,0%,0%
Rarely or never - for other reasons,33%,0%,0%,0%,0%

### child_self_drive_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",16%,0%,0%,0%,0%
Rarely or never - I'm too young,50%,0%,0%,0%,0%
Rarely or never - for other reasons,33%,0%,0%,0%,0%

## *Child_Self_Walk_Freq* (Each Column Adds Up To 100%):

### child_self_walk_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every day, or almost every day",33%,0%,0%,0%,0%,33%,33%
Once every few days,16%,0%,0%,0%,0%,33%,0%
Rarely or never,50%,0%,0%,0%,0%,33%,66%

### child_self_walk_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every day, or almost every day",33%,33%,100%,0%,0%,0%,0%,0%,0%,0%,0%
Once every few days,16%,33%,0%,0%,0%,0%,0%,0%,0%,0%,0%
Rarely or never,50%,33%,0%,100%,100%,0%,0%,0%,0%,0%,0%

### child_self_walk_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every day, or almost every day",33%,0%,0%,0%,0%,0%,0%
Once every few days,16%,0%,0%,0%,0%,0%,0%
Rarely or never,50%,0%,100%,0%,0%,100%,0%

### child_self_walk_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every day, or almost every day",33%,0%,0%,0%,0%
Once every few days,16%,0%,0%,0%,0%
Rarely or never,50%,0%,0%,0%,0%

### child_self_walk_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every day, or almost every day",33%,0%,0%,0%,0%
Once every few days,16%,0%,0%,0%,0%
Rarely or never,50%,0%,0%,0%,0%

## *Child_Self_Commutes* (Each Column Adds Up To 100%):

### child_self_commutes by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
No,66%,0%,0%,0%,0%,66%,66%
Yes,33%,0%,0%,0%,0%,33%,33%

### child_self_commutes by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
No,66%,66%,100%,0%,100%,0%,0%,0%,0%,0%,0%
Yes,33%,33%,0%,100%,0%,0%,0%,0%,0%,0%,0%

### child_self_commutes by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
No,66%,0%,0%,0%,0%,0%,0%
Yes,33%,0%,100%,0%,0%,100%,0%

### child_self_commutes by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
No,66%,0%,0%,0%,0%
Yes,33%,0%,0%,0%,0%

### child_self_commutes by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
No,66%,0%,0%,0%,0%
Yes,33%,0%,0%,0%,0%

## *Child_Self_Has_Children* (Each Column Adds Up To 100%):

### child_self_has_children by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
No,100%,0%,0%,0%,100%,0%,0%

### child_self_has_children by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
No,100%,100%,0%,100%,0%,100%,0%,0%,0%,0%,0%

### child_self_has_children by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
No,100%,100%,100%,100%,0%,0%,0%

### child_self_has_children by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
No,100%,100%,100%,100%,100%

### child_self_has_children by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
No,100%,0%,100%,100%,100%

## *Commuter_Type* (Each Column Adds Up To 100%):

### commuter_type by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
I bicycle the entire way (weather permitting),0%,1%,0%,0%,0%,0%,0%
I drive the entire way,43%,40%,45%,60%,25%,0%,100%
I take a bus the entire way,0%,0%,0%,0%,0%,100%,0%
I take the train at Croton Harmon,53%,56%,51%,40%,50%,0%,0%
I take the train at another station,0%,0%,0%,0%,0%,0%,0%
I walk the entire way (weather permitting),1%,0%,1%,0%,25%,0%,0%

### commuter_type by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
I bicycle the entire way (weather permitting),0%,1%,1%,0%,2%,0%,0%,0%,0%,0%,0%
I drive the entire way,43%,43%,43%,39%,43%,46%,43%,71%,25%,25%,100%
I take a bus the entire way,0%,0%,1%,2%,0%,0%,0%,0%,0%,0%,0%
I take the train at Croton Harmon,53%,53%,54%,56%,53%,53%,56%,28%,75%,25%,0%
I take the train at another station,0%,0%,0%,0%,0%,0%,0%,0%,0%,50%,0%
I walk the entire way (weather permitting),1%,2%,0%,2%,0%,0%,0%,0%,0%,0%,0%

### commuter_type by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
I bicycle the entire way (weather permitting),0%,0%,0%,0%,100%,0%,0%
I drive the entire way,43%,0%,100%,0%,0%,0%,0%
I take a bus the entire way,0%,0%,0%,0%,0%,100%,0%
I take the train at Croton Harmon,53%,100%,0%,0%,0%,0%,0%
I take the train at another station,0%,0%,0%,0%,0%,0%,100%
I walk the entire way (weather permitting),1%,0%,0%,100%,0%,0%,0%

### commuter_type by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
I bicycle the entire way (weather permitting),0%,0%,0%,0%,8%
I drive the entire way,43%,50%,46%,26%,13%
I take a bus the entire way,0%,0%,0%,0%,0%
I take the train at Croton Harmon,53%,46%,52%,73%,78%
I take the train at another station,0%,1%,0%,0%,0%
I walk the entire way (weather permitting),1%,1%,1%,0%,0%

### commuter_type by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
I bicycle the entire way (weather permitting),0%,0%,0%,0%,3%
I drive the entire way,43%,43%,44%,37%,55%
I take a bus the entire way,0%,0%,0%,0%,0%
I take the train at Croton Harmon,53%,52%,52%,61%,40%
I take the train at another station,0%,0%,0%,1%,0%
I walk the entire way (weather permitting),1%,2%,0%,0%,0%

## *Commuter_Walk_To_Station_Freq* (Each Column Adds Up To 100%):

### commuter_walk_to_station_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every trip, or almost every trip",14%,14%,13%,20%,0%,0%,0%
Once every few trips,8%,8%,6%,10%,50%,0%,0%
Once in a while,17%,16%,23%,0%,0%,0%,0%
Rarely or never,59%,59%,56%,70%,50%,0%,0%

### commuter_walk_to_station_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every trip, or almost every trip",14%,38%,5%,7%,0%,5%,0%,50%,0%,0%,0%
Once every few trips,8%,21%,7%,3%,0%,0%,0%,0%,0%,0%,0%
Once in a while,17%,23%,20%,18%,4%,35%,0%,0%,0%,0%,0%
Rarely or never,59%,17%,67%,70%,95%,58%,100%,50%,100%,100%,0%

### commuter_walk_to_station_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every trip, or almost every trip",14%,14%,0%,0%,0%,0%,0%
Once every few trips,8%,8%,0%,0%,0%,0%,0%
Once in a while,17%,17%,0%,0%,0%,0%,0%
Rarely or never,59%,59%,0%,0%,0%,0%,0%

### commuter_walk_to_station_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every trip, or almost every trip",14%,15%,17%,6%,11%
Once every few trips,8%,1%,8%,25%,11%
Once in a while,17%,10%,17%,25%,38%
Rarely or never,59%,72%,55%,43%,38%

### commuter_walk_to_station_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every trip, or almost every trip",14%,34%,6%,4%,9%
Once every few trips,8%,12%,9%,4%,0%
Once in a while,17%,16%,24%,12%,9%
Rarely or never,59%,36%,60%,79%,81%

## *Commuter_Bike_To_Station_Freq* (Each Column Adds Up To 100%):

### commuter_bike_to_station_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every trip, or almost every trip",7%,6%,7%,0%,50%,0%,0%
Once every few trips,6%,6%,6%,0%,0%,0%,0%
Once in a while,10%,11%,10%,0%,0%,0%,0%
Rarely or never,76%,74%,75%,100%,50%,0%,0%

### commuter_bike_to_station_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every trip, or almost every trip",7%,11%,7%,7%,0%,11%,0%,0%,0%,0%,0%
Once every few trips,6%,11%,7%,0%,0%,5%,11%,0%,0%,0%,0%
Once in a while,10%,15%,5%,11%,9%,17%,11%,0%,0%,0%,0%
Rarely or never,76%,61%,80%,81%,90%,64%,77%,100%,100%,100%,0%

### commuter_bike_to_station_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every trip, or almost every trip",7%,7%,0%,0%,0%,0%,0%
Once every few trips,6%,6%,0%,0%,0%,0%,0%
Once in a while,10%,10%,0%,0%,0%,0%,0%
Rarely or never,76%,75%,0%,0%,0%,0%,0%

### commuter_bike_to_station_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every trip, or almost every trip",7%,0%,0%,9%,55%
Once every few trips,6%,0%,0%,28%,11%
Once in a while,10%,2%,13%,21%,22%
Rarely or never,76%,97%,86%,40%,11%

### commuter_bike_to_station_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every trip, or almost every trip",7%,14%,1%,6%,9%
Once every few trips,6%,7%,4%,6%,9%
Once in a while,10%,10%,12%,10%,0%
Rarely or never,76%,67%,81%,77%,81%

## *Commuter_Drive_To_Station_Freq* (Each Column Adds Up To 100%):

### commuter_drive_to_station_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every trip, or almost every trip",56%,52%,64%,30%,100%,0%,0%
Once every few trips,9%,11%,7%,0%,0%,0%,0%
Once in a while,13%,11%,10%,50%,0%,0%,0%
Rarely or never,21%,23%,16%,20%,0%,0%,0%

### commuter_drive_to_station_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every trip, or almost every trip",56%,26%,55%,77%,95%,76%,33%,0%,83%,50%,0%
Once every few trips,9%,9%,10%,14%,0%,17%,11%,0%,0%,0%,0%
Once in a while,13%,25%,7%,3%,0%,0%,55%,0%,0%,0%,0%
Rarely or never,21%,38%,27%,3%,4%,5%,0%,100%,16%,50%,0%

### commuter_drive_to_station_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every trip, or almost every trip",56%,56%,0%,0%,0%,0%,0%
Once every few trips,9%,9%,0%,0%,0%,0%,0%
Once in a while,13%,13%,0%,0%,0%,0%,0%
Rarely or never,21%,20%,0%,0%,0%,0%,0%

### commuter_drive_to_station_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every trip, or almost every trip",56%,63%,62%,53%,16%
Once every few trips,9%,5%,6%,12%,27%
Once in a while,13%,16%,6%,9%,16%
Rarely or never,21%,14%,24%,25%,38%

### commuter_drive_to_station_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every trip, or almost every trip",56%,38%,66%,63%,54%
Once every few trips,9%,7%,10%,8%,18%
Once in a while,13%,20%,9%,10%,18%
Rarely or never,21%,34%,13%,18%,9%

## *Commuter_Carpool_To_Station_Freq* (Each Column Adds Up To 100%):

### commuter_carpool_to_station_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every trip, or almost every trip",1%,0%,3%,0%,0%,0%,0%
Once every few trips,5%,6%,4%,0%,0%,0%,0%
Once in a while,9%,8%,12%,0%,0%,0%,0%
Rarely or never,83%,83%,80%,100%,100%,0%,0%

### commuter_carpool_to_station_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every trip, or almost every trip",1%,1%,0%,0%,4%,0%,11%,0%,0%,0%,0%
Once every few trips,5%,7%,2%,3%,0%,5%,0%,0%,16%,50%,0%
Once in a while,9%,9%,7%,11%,9%,0%,11%,0%,16%,0%,0%
Rarely or never,83%,80%,89%,85%,86%,94%,77%,100%,66%,50%,0%

### commuter_carpool_to_station_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every trip, or almost every trip",1%,1%,0%,0%,0%,0%,0%
Once every few trips,5%,5%,0%,0%,0%,0%,0%
Once in a while,9%,9%,0%,0%,0%,0%,0%
Rarely or never,83%,83%,0%,0%,0%,0%,0%

### commuter_carpool_to_station_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every trip, or almost every trip",1%,1%,2%,3%,0%
Once every few trips,5%,4%,6%,6%,5%
Once in a while,9%,8%,20%,3%,0%
Rarely or never,83%,85%,71%,87%,94%

### commuter_carpool_to_station_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every trip, or almost every trip",1%,1%,0%,2%,9%
Once every few trips,5%,0%,9%,6%,9%
Once in a while,9%,14%,10%,2%,9%
Rarely or never,83%,83%,79%,89%,72%

## *Commuter_Driven_To_Station_Freq* (Each Column Adds Up To 100%):

### commuter_driven_to_station_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every trip, or almost every trip",8%,6%,7%,30%,0%,0%,0%
Once every few trips,10%,10%,9%,10%,0%,0%,0%
Once in a while,26%,24%,27%,40%,50%,0%,0%
Rarely or never,54%,57%,55%,20%,50%,0%,0%

### commuter_driven_to_station_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every trip, or almost every trip",8%,5%,17%,0%,0%,5%,33%,0%,16%,0%,0%
Once every few trips,10%,11%,12%,14%,0%,5%,11%,0%,16%,0%,0%
Once in a while,26%,36%,15%,29%,36%,0%,33%,50%,16%,0%,0%
Rarely or never,54%,46%,55%,55%,63%,88%,22%,50%,50%,100%,0%

### commuter_driven_to_station_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every trip, or almost every trip",8%,8%,0%,0%,0%,0%,0%
Once every few trips,10%,10%,0%,0%,0%,0%,0%
Once in a while,26%,26%,0%,0%,0%,0%,0%
Rarely or never,54%,54%,0%,0%,0%,0%,0%

### commuter_driven_to_station_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every trip, or almost every trip",8%,10%,11%,6%,0%
Once every few trips,10%,11%,6%,9%,11%
Once in a while,26%,27%,28%,18%,33%
Rarely or never,54%,50%,53%,65%,55%

### commuter_driven_to_station_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every trip, or almost every trip",8%,5%,10%,12%,0%
Once every few trips,10%,14%,6%,10%,9%
Once in a while,26%,25%,30%,18%,45%
Rarely or never,54%,54%,52%,59%,45%

## *Commuter_Bus_To_Station_Freq* (Each Column Adds Up To 100%):

### commuter_bus_to_station_freq by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
"Every trip, or almost every trip",2%,1%,3%,10%,0%,0%,0%
Once every few trips,2%,1%,3%,0%,0%,0%,0%
Once in a while,1%,1%,1%,0%,0%,0%,0%
Rarely or never,93%,94%,92%,90%,100%,0%,0%

### commuter_bus_to_station_freq by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
"Every trip, or almost every trip",2%,0%,5%,0%,0%,0%,11%,50%,0%,0%,0%
Once every few trips,2%,0%,7%,0%,0%,0%,0%,50%,0%,0%,0%
Once in a while,1%,1%,5%,0%,0%,0%,0%,0%,0%,0%,0%
Rarely or never,93%,98%,82%,100%,100%,100%,88%,0%,100%,100%,0%

### commuter_bus_to_station_freq by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
"Every trip, or almost every trip",2%,2%,0%,0%,0%,0%,0%
Once every few trips,2%,2%,0%,0%,0%,0%,0%
Once in a while,1%,1%,0%,0%,0%,0%,0%
Rarely or never,93%,93%,0%,0%,0%,0%,0%

### commuter_bus_to_station_freq by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
"Every trip, or almost every trip",2%,4%,2%,0%,0%
Once every few trips,2%,1%,2%,3%,5%
Once in a while,1%,0%,4%,3%,0%
Rarely or never,93%,94%,91%,93%,94%

### commuter_bus_to_station_freq by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
"Every trip, or almost every trip",2%,0%,4%,4%,0%
Once every few trips,2%,3%,3%,0%,0%
Once in a while,1%,1%,1%,2%,0%
Rarely or never,93%,94%,90%,93%,100%

## *Drivers_Are_Safe* (Each Column Adds Up To 100%):

### drivers_are_safe by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
1.0,8%,11%,8%,5%,0%,0%,0%
2.0,29%,30%,29%,26%,40%,66%,33%
3.0,48%,48%,50%,45%,60%,0%,66%
4.0,13%,10%,12%,23%,0%,33%,0%

### drivers_are_safe by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
1.0,8%,11%,11%,3%,4%,10%,6%,10%,9%,0%,0%
2.0,29%,36%,29%,22%,25%,20%,29%,45%,18%,20%,0%
3.0,48%,38%,49%,59%,50%,54%,45%,35%,72%,70%,100%
4.0,13%,14%,9%,14%,19%,14%,19%,10%,0%,10%,0%

### drivers_are_safe by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
1.0,8%,10%,7%,0%,66%,50%,0%
2.0,29%,29%,29%,50%,0%,50%,50%
3.0,48%,50%,48%,50%,33%,0%,0%
4.0,13%,9%,13%,0%,0%,0%,50%

### drivers_are_safe by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
1.0,8%,6%,13%,11%,12%
2.0,29%,28%,28%,30%,32%
3.0,48%,47%,47%,47%,51%
4.0,13%,17%,10%,9%,3%

### drivers_are_safe by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
1.0,8%,15%,4%,4%,8%
2.0,29%,29%,35%,25%,19%
3.0,48%,43%,50%,50%,42%
4.0,13%,10%,9%,19%,29%

## *Bicyclists_Are_Safe* (Each Column Adds Up To 100%):

### bicyclists_are_safe by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
1.0,12%,12%,14%,10%,40%,0%,33%
2.0,22%,18%,21%,31%,20%,0%,0%
3.0,48%,51%,46%,47%,20%,33%,66%
4.0,15%,17%,17%,10%,20%,66%,0%

### bicyclists_are_safe by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
1.0,12%,13%,11%,13%,10%,16%,16%,10%,0%,10%,0%
2.0,22%,25%,26%,22%,19%,14%,22%,20%,9%,0%,0%
3.0,48%,46%,44%,50%,48%,54%,48%,60%,72%,80%,0%
4.0,15%,13%,17%,13%,21%,14%,12%,10%,18%,10%,100%

### bicyclists_are_safe by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
1.0,12%,11%,18%,0%,0%,0%,50%
2.0,22%,16%,23%,50%,0%,0%,0%
3.0,48%,49%,44%,50%,33%,0%,50%
4.0,15%,22%,13%,0%,66%,100%,0%

### bicyclists_are_safe by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
1.0,12%,15%,12%,5%,0%
2.0,22%,28%,15%,18%,3%
3.0,48%,44%,52%,55%,58%
4.0,15%,11%,20%,20%,37%

### bicyclists_are_safe by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
1.0,12%,13%,8%,13%,25%
2.0,22%,21%,24%,24%,19%
3.0,48%,50%,49%,46%,44%
4.0,15%,15%,17%,15%,10%

## *Contact_Interest* (Each Column Adds Up To 100%):

### contact_interest by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
No,53%,49%,53%,56%,60%,100%,100%
Yes,46%,50%,46%,43%,40%,0%,0%

### contact_interest by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
No,53%,51%,50%,54%,56%,52%,58%,60%,36%,60%,100%
Yes,46%,48%,49%,45%,43%,47%,41%,40%,63%,40%,0%

### contact_interest by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
No,53%,47%,55%,50%,33%,100%,50%
Yes,46%,52%,44%,50%,66%,0%,50%

### contact_interest by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
No,53%,59%,44%,39%,37%
Yes,46%,40%,55%,60%,62%

### contact_interest by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
No,53%,37%,51%,69%,66%
Yes,46%,62%,48%,30%,33%

## *Problem_Tags_129* (Each Column Adds Up To 100%):

### problem_tags_129 by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,90%,90%,90%,90%,100%,66%,100%
1,9%,9%,9%,9%,0%,33%,0%

### problem_tags_129 by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,90%,92%,86%,94%,95%,89%,90%,90%,63%,90%,100%
1,9%,7%,13%,5%,4%,10%,9%,9%,36%,10%,0%

### problem_tags_129 by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,90%,91%,92%,75%,66%,50%,100%
1,9%,8%,7%,25%,33%,50%,0%

### problem_tags_129 by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,90%,92%,90%,88%,80%
1,9%,7%,9%,11%,19%

### problem_tags_129 by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,90%,88%,92%,92%,91%
1,9%,11%,7%,7%,8%

## *Problem_Tags_Aggressive Driving* (Each Column Adds Up To 100%):

### problem_tags_aggressive driving by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,86%,83%,86%,92%,60%,66%,100%
1,13%,16%,13%,7%,40%,33%,0%

### problem_tags_aggressive driving by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,86%,82%,84%,89%,92%,85%,93%,90%,72%,100%,100%
1,13%,17%,15%,10%,7%,14%,6%,9%,27%,0%,0%

### problem_tags_aggressive driving by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,86%,82%,89%,75%,66%,100%,100%
1,13%,17%,10%,25%,33%,0%,0%

### problem_tags_aggressive driving by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,86%,91%,80%,84%,70%
1,13%,8%,19%,15%,29%

### problem_tags_aggressive driving by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,86%,84%,85%,88%,95%
1,13%,15%,14%,11%,4%

## *Problem_Tags_Benedict* (Each Column Adds Up To 100%):

### problem_tags_benedict by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,95%,94%,94%,97%,100%,100%,100%
1,4%,5%,5%,2%,0%,0%,0%

### problem_tags_benedict by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,95%,89%,97%,98%,98%,95%,100%,100%,100%,100%,100%
1,4%,10%,2%,1%,1%,4%,0%,0%,0%,0%,0%

### problem_tags_benedict by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,95%,92%,95%,100%,100%,100%,100%
1,4%,7%,4%,0%,0%,0%,0%

### problem_tags_benedict by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,95%,97%,94%,90%,96%
1,4%,2%,5%,9%,3%

### problem_tags_benedict by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,95%,93%,96%,98%,95%
1,4%,6%,3%,1%,4%

## *Problem_Tags_Bushes On Sidewalk* (Each Column Adds Up To 100%):

### problem_tags_bushes on sidewalk by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,94%,93%,97%,93%,100%,66%,100%
1,5%,6%,2%,6%,0%,33%,0%

### problem_tags_bushes on sidewalk by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,94%,92%,94%,94%,98%,95%,100%,95%,90%,90%,100%
1,5%,7%,5%,5%,1%,4%,0%,4%,9%,10%,0%

### problem_tags_bushes on sidewalk by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,94%,94%,96%,100%,100%,100%,100%
1,5%,5%,3%,0%,0%,0%,0%

### problem_tags_bushes on sidewalk by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,94%,94%,95%,94%,93%
1,5%,5%,4%,5%,6%

### problem_tags_bushes on sidewalk by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,94%,93%,92%,98%,100%
1,5%,6%,7%,1%,0%

## *Problem_Tags_Cet* (Each Column Adds Up To 100%):

### problem_tags_cet by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,95%,99%,99%,80%,100%,100%
1,2%,4%,0%,0%,20%,0%,0%

### problem_tags_cet by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,93%,100%,100%,98%,95%,100%,100%,100%,100%,100%
1,2%,6%,0%,0%,1%,4%,0%,0%,0%,0%,0%

### problem_tags_cet by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,97%,96%,100%,100%,100%,100%
1,2%,2%,3%,0%,0%,0%,0%

### problem_tags_cet by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,98%,94%,98%,100%
1,2%,1%,5%,1%,0%

### problem_tags_cet by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,97%,97%,97%,100%
1,2%,2%,2%,2%,0%

## *Problem_Tags_Cleveland* (Each Column Adds Up To 100%):

### problem_tags_cleveland by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,92%,88%,94%,94%,80%,100%,100%
1,7%,11%,5%,5%,20%,0%,0%

### problem_tags_cleveland by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,92%,83%,92%,98%,98%,91%,100%,100%,90%,100%,100%
1,7%,16%,7%,1%,1%,8%,0%,0%,9%,0%,0%

### problem_tags_cleveland by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,92%,92%,91%,100%,100%,100%,100%
1,7%,7%,8%,0%,0%,0%,0%

### problem_tags_cleveland by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,92%,92%,89%,92%,96%
1,7%,7%,10%,7%,3%

### problem_tags_cleveland by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,92%,90%,91%,94%,97%
1,7%,9%,8%,5%,2%

## *Problem_Tags_Cpa* (Each Column Adds Up To 100%):

### problem_tags_cpa by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,84%,78%,82%,96%,60%,100%,100%
1,15%,21%,17%,3%,40%,0%,0%

### problem_tags_cpa by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,84%,71%,88%,93%,86%,83%,96%,100%,81%,100%,100%
1,15%,28%,11%,6%,13%,16%,3%,0%,18%,0%,0%

### problem_tags_cpa by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,84%,69%,89%,75%,66%,100%,100%
1,15%,30%,10%,25%,33%,0%,0%

### problem_tags_cpa by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,84%,89%,83%,74%,51%
1,15%,10%,16%,25%,48%

### problem_tags_cpa by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,84%,84%,82%,83%,91%
1,15%,15%,17%,16%,8%

## *Problem_Tags_Crossing Guard* (Each Column Adds Up To 100%):

### problem_tags_crossing guard by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,96%,97%,98%,80%,100%,100%
1,3%,3%,2%,1%,20%,0%,0%

### problem_tags_crossing guard by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,95%,96%,100%,97%,97%,96%,100%,90%,100%,100%
1,3%,4%,3%,0%,2%,2%,3%,0%,9%,0%,0%

### problem_tags_crossing guard by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,96%,96%,75%,100%,50%,100%
1,3%,3%,3%,25%,0%,50%,0%

### problem_tags_crossing guard by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,96%,98%,98%,96%
1,3%,3%,1%,1%,3%

### problem_tags_crossing guard by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,97%,97%,95%,95%
1,3%,2%,2%,4%,4%

## *Problem_Tags_Croton Commons* (Each Column Adds Up To 100%):

### problem_tags_croton commons by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,96%,95%,100%,100%,100%,100%
1,2%,3%,4%,0%,0%,0%,0%

### problem_tags_croton commons by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,95%,99%,96%,98%,95%,100%,100%,100%,100%,100%
1,2%,4%,0%,3%,1%,4%,0%,0%,0%,0%,0%

### problem_tags_croton commons by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,99%,95%,100%,100%,100%,100%
1,2%,0%,4%,0%,0%,0%,0%

### problem_tags_croton commons by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,98%,95%,98%,90%
1,2%,1%,4%,1%,9%

### problem_tags_croton commons by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,95%,98%,98%,100%
1,2%,4%,1%,1%,0%

## *Problem_Tags_Cyclists Breaking Rules* (Each Column Adds Up To 100%):

### problem_tags_cyclists breaking rules by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,91%,95%,87%,89%,100%,100%,100%
1,8%,4%,12%,10%,0%,0%,0%

### problem_tags_cyclists breaking rules by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,91%,89%,91%,85%,95%,95%,93%,95%,100%,100%,100%
1,8%,10%,8%,14%,4%,4%,6%,4%,0%,0%,0%

### problem_tags_cyclists breaking rules by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,91%,94%,89%,100%,100%,100%,100%
1,8%,5%,10%,0%,0%,0%,0%

### problem_tags_cyclists breaking rules by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,91%,89%,93%,95%,93%
1,8%,10%,6%,4%,6%

### problem_tags_cyclists breaking rules by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,91%,89%,94%,91%,87%
1,8%,10%,5%,8%,12%

## *Problem_Tags_Driver Awareness* (Each Column Adds Up To 100%):

### problem_tags_driver awareness by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,86%,85%,85%,89%,80%,100%,100%
1,13%,14%,14%,10%,20%,0%,0%

### problem_tags_driver awareness by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,86%,83%,88%,87%,88%,87%,90%,85%,81%,90%,100%
1,13%,16%,11%,12%,11%,12%,9%,14%,18%,10%,0%

### problem_tags_driver awareness by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,86%,83%,89%,100%,100%,100%,50%
1,13%,16%,10%,0%,0%,0%,50%

### problem_tags_driver awareness by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,86%,86%,89%,85%,77%
1,13%,13%,10%,14%,22%

### problem_tags_driver awareness by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,86%,86%,85%,85%,91%
1,13%,13%,14%,14%,8%

## *Problem_Tags_Dummy Light* (Each Column Adds Up To 100%):

### problem_tags_dummy light by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,96%,97%,95%,80%,100%,100%
1,3%,3%,2%,4%,20%,0%,0%

### problem_tags_dummy light by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,97%,94%,96%,97%,100%,100%,100%,100%,80%,100%
1,3%,2%,5%,3%,2%,0%,0%,0%,0%,20%,0%

### problem_tags_dummy light by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,97%,97%,100%,100%,100%,50%
1,3%,2%,2%,0%,0%,0%,50%

### problem_tags_dummy light by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,96%,95%,97%,96%
1,3%,3%,4%,2%,3%

### problem_tags_dummy light by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,95%,97%,95%,100%
1,3%,4%,2%,4%,0%

## *Problem_Tags_Five Corners* (Each Column Adds Up To 100%):

### problem_tags_five corners by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,95%,96%,95%,100%,100%,100%
1,3%,4%,3%,4%,0%,0%,0%

### problem_tags_five corners by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,93%,96%,100%,98%,97%,96%,90%,90%,100%,100%
1,3%,6%,3%,0%,1%,2%,3%,9%,9%,0%,0%

### problem_tags_five corners by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,97%,96%,50%,100%,100%,100%
1,3%,2%,3%,50%,0%,0%,0%

### problem_tags_five corners by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,95%,94%,98%,100%
1,3%,4%,5%,1%,0%

### problem_tags_five corners by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,93%,96%,98%,97%
1,3%,6%,3%,1%,2%

## *Problem_Tags_Gottwald Circle* (Each Column Adds Up To 100%):

### problem_tags_gottwald circle by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,97%,97%,95%,100%,66%,100%
1,3%,2%,2%,4%,0%,33%,0%

### problem_tags_gottwald circle by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,90%,99%,100%,100%,97%,100%,100%,100%,100%,100%
1,3%,9%,0%,0%,0%,2%,0%,0%,0%,0%,0%

### problem_tags_gottwald circle by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,98%,96%,100%,100%,100%,100%
1,3%,1%,3%,0%,0%,0%,0%

### problem_tags_gottwald circle by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,96%,95%,100%,100%
1,3%,3%,4%,0%,0%

### problem_tags_gottwald circle by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,95%,97%,98%,97%
1,3%,4%,2%,1%,2%

## *Problem_Tags_Grand* (Each Column Adds Up To 100%):

### problem_tags_grand by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,95%,95%,95%,95%,100%,100%,100%
1,4%,4%,4%,5%,0%,0%,0%

### problem_tags_grand by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,95%,99%,88%,94%,95%,100%,100%,100%,81%,80%,100%
1,4%,0%,11%,5%,4%,0%,0%,0%,18%,20%,0%

### problem_tags_grand by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,95%,94%,95%,100%,100%,100%,50%
1,4%,5%,4%,0%,0%,0%,50%

### problem_tags_grand by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,95%,95%,94%,94%,93%
1,4%,4%,5%,5%,6%

### problem_tags_grand by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,95%,95%,93%,96%,97%
1,4%,4%,6%,3%,2%

## *Problem_Tags_Hmb Trail* (Each Column Adds Up To 100%):

### problem_tags_hmb trail by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,99%,96%,95%,100%,100%,100%
1,2%,0%,3%,4%,0%,0%,0%

### problem_tags_hmb trail by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,98%,97%,100%,98%,93%,96%,90%,100%,100%,100%
1,2%,1%,2%,0%,1%,6%,3%,9%,0%,0%,0%

### problem_tags_hmb trail by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,98%,98%,100%,100%,100%,100%
1,2%,1%,1%,0%,0%,0%,0%

### problem_tags_hmb trail by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,99%,96%,94%,90%
1,2%,0%,3%,5%,9%

### problem_tags_hmb trail by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,97%,95%,100%,100%
1,2%,2%,4%,0%,0%

## *Problem_Tags_Maple* (Each Column Adds Up To 100%):

### problem_tags_maple by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,91%,88%,93%,93%,100%,100%,100%
1,8%,11%,6%,6%,0%,0%,0%

### problem_tags_maple by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,91%,92%,82%,94%,95%,95%,96%,85%,100%,90%,100%
1,8%,7%,17%,5%,4%,4%,3%,14%,0%,10%,0%

### problem_tags_maple by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,91%,90%,90%,100%,66%,100%,100%
1,8%,9%,9%,0%,33%,0%,0%

### problem_tags_maple by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,91%,92%,91%,88%,90%
1,8%,7%,8%,11%,9%

### problem_tags_maple by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,91%,86%,92%,93%,97%
1,8%,13%,7%,6%,2%

## *Problem_Tags_Missing Crosswalks* (Each Column Adds Up To 100%):

### problem_tags_missing crosswalks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,94%,93%,92%,96%,100%,66%,100%
1,5%,6%,7%,3%,0%,33%,0%

### problem_tags_missing crosswalks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,94%,90%,94%,94%,98%,97%,96%,95%,100%,80%,100%
1,5%,9%,5%,5%,1%,2%,3%,4%,0%,20%,0%

### problem_tags_missing crosswalks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,94%,94%,93%,100%,100%,100%,100%
1,5%,5%,6%,0%,0%,0%,0%

### problem_tags_missing crosswalks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,94%,93%,96%,94%,100%
1,5%,6%,3%,5%,0%

### problem_tags_missing crosswalks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,94%,91%,95%,96%,100%
1,5%,8%,4%,3%,0%

## *Problem_Tags_Missing Sidewalks* (Each Column Adds Up To 100%):

### problem_tags_missing sidewalks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,78%,74%,75%,87%,80%,100%,66%
1,21%,25%,24%,12%,20%,0%,33%

### problem_tags_missing sidewalks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,78%,78%,72%,84%,79%,79%,87%,71%,81%,70%,100%
1,21%,21%,27%,15%,20%,20%,12%,28%,18%,30%,0%

### problem_tags_missing sidewalks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,78%,75%,82%,75%,66%,100%,100%
1,21%,24%,17%,25%,33%,0%,0%

### problem_tags_missing sidewalks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,78%,79%,75%,83%,70%
1,21%,20%,24%,16%,29%

### problem_tags_missing sidewalks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,78%,71%,76%,85%,95%
1,21%,28%,23%,14%,4%

## *Problem_Tags_Morningside* (Each Column Adds Up To 100%):

### problem_tags_morningside by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,97%,98%,99%,100%,100%,100%
1,1%,2%,1%,0%,0%,0%,0%

### problem_tags_morningside by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,96%,99%,100%,100%,93%,100%,100%,100%,100%,100%
1,1%,3%,0%,0%,0%,6%,0%,0%,0%,0%,0%

### problem_tags_morningside by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,98%,95%,100%,100%,100%,100%
1,1%,1%,4%,0%,0%,0%,0%

### problem_tags_morningside by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,98%,98%,100%
1,1%,1%,1%,1%,0%

### problem_tags_morningside by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,95%,99%,100%,100%
1,1%,4%,0%,0%,0%

## *Problem_Tags_Mt Airy* (Each Column Adds Up To 100%):

### problem_tags_mt airy by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,95%,93%,95%,98%,100%,100%,66%
1,4%,6%,4%,1%,0%,0%,33%

### problem_tags_mt airy by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,95%,98%,100%,100%,70%,97%,100%,90%,100%,100%,100%
1,4%,1%,0%,0%,29%,2%,0%,9%,0%,0%,0%

### problem_tags_mt airy by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,95%,94%,96%,100%,66%,100%,100%
1,4%,5%,3%,0%,33%,0%,0%

### problem_tags_mt airy by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,95%,94%,96%,97%,96%
1,4%,5%,3%,2%,3%

### problem_tags_mt airy by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,95%,96%,95%,93%,95%
1,4%,3%,4%,6%,4%

## *Problem_Tags_Municipal Place* (Each Column Adds Up To 100%):

### problem_tags_municipal place by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,93%,90%,92%,97%,80%,100%,100%
1,6%,9%,7%,2%,20%,0%,0%

### problem_tags_municipal place by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,93%,94%,88%,89%,95%,97%,100%,80%,100%,100%,100%
1,6%,5%,11%,10%,4%,2%,0%,19%,0%,0%,0%

### problem_tags_municipal place by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,93%,90%,93%,100%,100%,100%,100%
1,6%,9%,6%,0%,0%,0%,0%

### problem_tags_municipal place by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,93%,93%,93%,90%,87%
1,6%,6%,6%,9%,12%

### problem_tags_municipal place by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,93%,91%,93%,92%,95%
1,6%,8%,6%,7%,4%

## *Problem_Tags_N Riverside* (Each Column Adds Up To 100%):

### problem_tags_n riverside by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,97%,95%,97%,80%,100%,100%
1,3%,2%,4%,2%,20%,0%,0%

### problem_tags_n riverside by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,98%,96%,90%,98%,100%,90%,100%,100%,100%,100%
1,3%,1%,3%,9%,1%,0%,9%,0%,0%,0%,0%

### problem_tags_n riverside by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,95%,99%,75%,100%,100%,100%
1,3%,4%,0%,25%,0%,0%,0%

### problem_tags_n riverside by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,99%,94%,94%,93%
1,3%,0%,5%,5%,6%

### problem_tags_n riverside by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,96%,96%,96%,100%
1,3%,3%,3%,3%,0%

## *Problem_Tags_Narrow Roads* (Each Column Adds Up To 100%):

### problem_tags_narrow roads by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,95%,92%,96%,98%,100%,100%,100%
1,4%,7%,3%,1%,0%,0%,0%

### problem_tags_narrow roads by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,95%,95%,97%,94%,89%,95%,100%,90%,100%,100%,100%
1,4%,4%,2%,5%,10%,4%,0%,9%,0%,0%,0%

### problem_tags_narrow roads by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,95%,97%,94%,100%,100%,100%,100%
1,4%,2%,5%,0%,0%,0%,0%

### problem_tags_narrow roads by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,95%,95%,94%,98%,96%
1,4%,4%,5%,1%,3%

### problem_tags_narrow roads by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,95%,95%,97%,95%,93%
1,4%,4%,2%,4%,6%

## *Problem_Tags_Olcott* (Each Column Adds Up To 100%):

### problem_tags_olcott by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,97%,97%,99%,100%,100%,100%
1,2%,2%,2%,0%,0%,0%,0%

### problem_tags_olcott by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,97%,94%,100%,100%,100%,100%,95%,100%,100%,100%
1,2%,2%,5%,0%,0%,0%,0%,4%,0%,0%,0%

### problem_tags_olcott by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,96%,98%,100%,100%,100%,100%
1,2%,3%,1%,0%,0%,0%,0%

### problem_tags_olcott by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,98%,97%,98%,96%
1,2%,1%,2%,1%,3%

### problem_tags_olcott by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,97%,97%,98%,100%
1,2%,2%,2%,1%,0%

## *Problem_Tags_Old Post N* (Each Column Adds Up To 100%):

### problem_tags_old post n by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,97%,97%,98%,100%,100%,100%
1,2%,2%,2%,1%,0%,0%,0%

### problem_tags_old post n by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,99%,99%,90%,100%,97%,96%,100%,100%,90%,100%
1,2%,0%,0%,9%,0%,2%,3%,0%,0%,10%,0%

### problem_tags_old post n by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,98%,97%,100%,100%,100%,50%
1,2%,1%,2%,0%,0%,0%,50%

### problem_tags_old post n by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,97%,97%,100%,96%
1,2%,2%,2%,0%,3%

### problem_tags_old post n by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,99%,95%,99%,97%
1,2%,0%,4%,0%,2%

## *Problem_Tags_Old Post S* (Each Column Adds Up To 100%):

### problem_tags_old post s by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,97%,98%,97%,100%,100%,100%
1,1%,2%,1%,2%,0%,0%,0%

### problem_tags_old post s by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,96%,100%,97%,98%,97%,100%,95%,100%,100%,100%
1,1%,3%,0%,2%,1%,2%,0%,4%,0%,0%,0%

### problem_tags_old post s by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,98%,97%,100%,100%,100%,100%
1,1%,1%,2%,0%,0%,0%,0%

### problem_tags_old post s by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,97%,97%,98%,100%
1,1%,2%,2%,1%,0%

### problem_tags_old post s by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,97%,97%,99%,100%
1,1%,2%,2%,0%,0%

## *Problem_Tags_On-Street Parking* (Each Column Adds Up To 100%):

### problem_tags_on-street parking by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,96%,99%,98%,100%,100%,100%
1,2%,3%,0%,1%,0%,0%,0%

### problem_tags_on-street parking by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,99%,98%,97%,95%,93%,100%,100%,100%,100%,100%
1,2%,0%,1%,2%,4%,6%,0%,0%,0%,0%,0%

### problem_tags_on-street parking by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,97%,97%,100%,100%,100%,100%
1,2%,2%,2%,0%,0%,0%,0%

### problem_tags_on-street parking by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,97%,97%,100%,93%
1,2%,2%,2%,0%,6%

### problem_tags_on-street parking by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,96%,99%,97%,95%
1,2%,3%,0%,2%,4%

## *Problem_Tags_Poor Lighting* (Each Column Adds Up To 100%):

### problem_tags_poor lighting by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,96%,98%,97%,60%,100%,100%
1,3%,3%,1%,2%,40%,0%,0%

### problem_tags_poor lighting by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,96%,97%,96%,98%,91%,100%,100%,100%,100%,100%
1,3%,3%,2%,3%,1%,8%,0%,0%,0%,0%,0%

### problem_tags_poor lighting by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,96%,95%,75%,100%,100%,100%
1,3%,3%,4%,25%,0%,0%,0%

### problem_tags_poor lighting by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,97%,94%,97%,96%
1,3%,2%,5%,2%,3%

### problem_tags_poor lighting by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,96%,97%,96%,100%
1,3%,3%,2%,3%,0%

## *Problem_Tags_Road Surface* (Each Column Adds Up To 100%):

### problem_tags_road surface by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,91%,92%,91%,90%,100%,100%,100%
1,8%,7%,8%,9%,0%,0%,0%

### problem_tags_road surface by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,91%,91%,94%,90%,94%,85%,93%,95%,81%,100%,100%
1,8%,8%,5%,9%,5%,14%,6%,4%,18%,0%,0%

### problem_tags_road surface by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,91%,94%,91%,100%,100%,100%,100%
1,8%,5%,8%,0%,0%,0%,0%

### problem_tags_road surface by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,91%,92%,90%,91%,83%
1,8%,7%,9%,8%,16%

### problem_tags_road surface by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,91%,92%,93%,89%,85%
1,8%,7%,6%,10%,14%

## *Problem_Tags_S Riverside* (Each Column Adds Up To 100%):

### problem_tags_s riverside by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,87%,82%,88%,92%,100%,100%,100%
1,12%,17%,11%,7%,0%,0%,0%

### problem_tags_s riverside by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,87%,78%,91%,89%,91%,91%,93%,80%,90%,100%,100%
1,12%,21%,8%,10%,8%,8%,6%,19%,9%,0%,0%

### problem_tags_s riverside by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,87%,79%,94%,75%,66%,100%,100%
1,12%,20%,5%,25%,33%,0%,0%

### problem_tags_s riverside by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,87%,92%,86%,74%,64%
1,12%,7%,13%,25%,35%

### problem_tags_s riverside by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,87%,83%,88%,89%,89%
1,12%,16%,11%,10%,10%

## *Problem_Tags_Shoprite* (Each Column Adds Up To 100%):

### problem_tags_shoprite by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,95%,93%,94%,99%,100%,100%,100%
1,4%,6%,5%,0%,0%,0%,0%

### problem_tags_shoprite by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,95%,89%,95%,100%,95%,100%,100%,95%,100%,100%,100%
1,4%,10%,4%,0%,4%,0%,0%,4%,0%,0%,0%

### problem_tags_shoprite by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,95%,97%,91%,100%,66%,100%,100%
1,4%,2%,8%,0%,33%,0%,0%

### problem_tags_shoprite by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,95%,97%,92%,91%,93%
1,4%,2%,7%,8%,6%

### problem_tags_shoprite by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,95%,94%,93%,96%,100%
1,4%,5%,6%,3%,0%

## *Problem_Tags_Sidewalk Condition* (Each Column Adds Up To 100%):

### problem_tags_sidewalk condition by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,85%,84%,82%,87%,100%,100%,100%
1,14%,15%,17%,12%,0%,0%,0%

### problem_tags_sidewalk condition by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,85%,82%,77%,88%,92%,75%,100%,90%,100%,100%,100%
1,14%,17%,22%,11%,7%,25%,0%,9%,0%,0%,0%

### problem_tags_sidewalk condition by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,85%,87%,81%,100%,100%,100%,100%
1,14%,12%,18%,0%,0%,0%,0%

### problem_tags_sidewalk condition by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,85%,84%,88%,83%,93%
1,14%,15%,11%,16%,6%

### problem_tags_sidewalk condition by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,85%,80%,81%,96%,91%
1,14%,19%,18%,3%,8%

## *Problem_Tags_Speeding* (Each Column Adds Up To 100%):

### problem_tags_speeding by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,77%,75%,79%,78%,80%,100%,100%
1,22%,24%,20%,21%,20%,0%,0%

### problem_tags_speeding by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,77%,73%,73%,77%,79%,85%,87%,90%,72%,90%,100%
1,22%,26%,26%,22%,20%,14%,12%,9%,27%,10%,0%

### problem_tags_speeding by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,77%,76%,79%,50%,100%,100%,50%
1,22%,23%,20%,50%,0%,0%,50%

### problem_tags_speeding by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,77%,76%,76%,83%,77%
1,22%,23%,23%,16%,22%

### problem_tags_speeding by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,77%,69%,78%,84%,82%
1,22%,30%,21%,15%,17%

## *Problem_Tags_Truesdale* (Each Column Adds Up To 100%):

### problem_tags_truesdale by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,96%,97%,98%,100%,100%,100%
1,2%,3%,2%,1%,0%,0%,0%

### problem_tags_truesdale by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,93%,100%,100%,100%,91%,100%,100%,100%,100%,100%
1,2%,6%,0%,0%,0%,8%,0%,0%,0%,0%,0%

### problem_tags_truesdale by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,98%,95%,100%,100%,100%,100%
1,2%,1%,4%,0%,0%,0%,0%

### problem_tags_truesdale by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,97%,97%,97%,100%
1,2%,2%,2%,2%,0%

### problem_tags_truesdale by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,94%,97%,100%,100%
1,2%,5%,2%,0%,0%

## *Problem_Tags_Van Wyck* (Each Column Adds Up To 100%):

### problem_tags_van wyck by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,96%,95%,97%,100%,100%,100%
1,3%,3%,4%,2%,0%,0%,0%

### problem_tags_van wyck by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,96%,94%,96%,98%,95%,100%,85%,100%,100%,100%
1,3%,3%,5%,3%,1%,4%,0%,14%,0%,0%,0%

### problem_tags_van wyck by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,96%,96%,100%,100%,100%,100%
1,3%,3%,3%,0%,0%,0%,0%

### problem_tags_van wyck by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,96%,97%,95%,90%
1,3%,3%,2%,4%,9%

### problem_tags_van wyck by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,93%,96%,98%,100%
1,3%,6%,3%,1%,0%

## *Schools_Cet* (Each Column Adds Up To 100%):

### schools_CET by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,81%,55%,100%,100%,100%,100%,100%
1,18%,44%,0%,0%,0%,0%,0%

### schools_CET by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,81%,81%,77%,77%,79%,75%,100%,100%,100%,80%,100%
1,18%,18%,22%,22%,20%,25%,0%,0%,0%,20%,0%

### schools_CET by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,81%,70%,83%,100%,66%,100%,100%
1,18%,29%,16%,0%,33%,0%,0%

### schools_CET by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,81%,81%,80%,80%,74%
1,18%,18%,19%,19%,25%

### schools_CET by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,81%,78%,81%,79%,87%
1,18%,21%,18%,20%,12%

## *Schools_Chhs* (Each Column Adds Up To 100%):

### schools_CHHS by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,87%,69%,100%,100%,100%,100%,100%
1,12%,30%,0%,0%,0%,0%,0%

### schools_CHHS by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,87%,91%,89%,81%,80%,87%,87%,85%,72%,100%,100%
1,12%,8%,10%,18%,19%,12%,12%,14%,27%,0%,0%

### schools_CHHS by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,87%,85%,79%,100%,100%,100%,100%
1,12%,14%,20%,0%,0%,0%,0%

### schools_CHHS by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,87%,88%,78%,91%,90%
1,12%,11%,21%,8%,9%

### schools_CHHS by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,87%,91%,84%,85%,85%
1,12%,8%,15%,14%,14%

## *Schools_Homeschooled* (Each Column Adds Up To 100%):

### schools_Homeschooled by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,99%,97%,100%,100%,100%,100%,100%
1,0%,2%,0%,0%,0%,0%,0%

### schools_Homeschooled by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,99%,98%,99%,100%,98%,100%,100%,100%,90%,100%,100%
1,0%,1%,0%,0%,1%,0%,0%,0%,9%,0%,0%

### schools_Homeschooled by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,99%,98%,99%,100%,100%,100%,100%
1,0%,1%,0%,0%,0%,0%,0%

### schools_Homeschooled by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,99%,99%,100%,98%,96%
1,0%,0%,0%,1%,3%

### schools_Homeschooled by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,99%,98%,98%,99%,100%
1,0%,1%,1%,0%,0%

## *Schools_Pvc* (Each Column Adds Up To 100%):

### schools_PVC by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,86%,66%,100%,100%,100%,100%,100%
1,13%,33%,0%,0%,0%,0%,0%

### schools_PVC by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,86%,89%,86%,81%,71%,79%,100%,95%,90%,100%,100%
1,13%,10%,13%,18%,28%,20%,0%,4%,9%,0%,0%

### schools_PVC by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,86%,79%,85%,75%,66%,50%,100%
1,13%,20%,14%,25%,33%,50%,0%

### schools_PVC by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,86%,87%,79%,87%,80%
1,13%,12%,20%,12%,19%

### schools_PVC by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,86%,87%,84%,85%,82%
1,13%,12%,15%,14%,17%

## *Suggestion_Tags_Better Lighting* (Each Column Adds Up To 100%):

### suggestion_tags_better lighting by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,96%,99%,99%,60%,100%,100%
1,2%,3%,0%,0%,40%,0%,0%

### suggestion_tags_better lighting by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,98%,97%,94%,100%,95%,100%,100%,100%,100%,100%
1,2%,1%,2%,5%,0%,4%,0%,0%,0%,0%,0%

### suggestion_tags_better lighting by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,96%,97%,75%,100%,100%,100%
1,2%,3%,2%,25%,0%,0%,0%

### suggestion_tags_better lighting by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,98%,95%,97%,100%
1,2%,1%,4%,2%,0%

### suggestion_tags_better lighting by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,97%,98%,96%,100%
1,2%,2%,1%,3%,0%

## *Suggestion_Tags_Bike Lanes* (Each Column Adds Up To 100%):

### suggestion_tags_bike lanes by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,81%,78%,81%,86%,60%,100%,66%
1,18%,21%,18%,13%,40%,0%,33%

### suggestion_tags_bike lanes by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,81%,78%,85%,80%,88%,79%,70%,71%,81%,100%,100%
1,18%,21%,14%,19%,11%,20%,29%,28%,18%,0%,0%

### suggestion_tags_bike lanes by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,81%,75%,84%,75%,33%,100%,100%
1,18%,24%,15%,25%,66%,0%,0%

### suggestion_tags_bike lanes by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,81%,89%,72%,71%,64%
1,18%,10%,27%,28%,35%

### suggestion_tags_bike lanes by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,81%,79%,77%,88%,89%
1,18%,20%,22%,11%,10%

## *Suggestion_Tags_Bike Racks* (Each Column Adds Up To 100%):

### suggestion_tags_bike racks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,98%,98%,99%,100%,100%,100%
1,1%,1%,1%,0%,0%,0%,0%

### suggestion_tags_bike racks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,98%,98%,98%,100%,97%,100%,100%,100%,100%,100%
1,1%,1%,1%,1%,0%,2%,0%,0%,0%,0%,0%

### suggestion_tags_bike racks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,98%,100%,100%,100%,100%,100%
1,1%,1%,0%,0%,0%,0%,0%

### suggestion_tags_bike racks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,99%,98%,97%,100%
1,1%,0%,1%,2%,0%

### suggestion_tags_bike racks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,98%,98%,99%,100%
1,1%,1%,1%,0%,0%

## *Suggestion_Tags_Dedicated Pedestrian Walk Signals* (Each Column Adds Up To 100%):

### suggestion_tags_dedicated pedestrian walk signals by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,98%,97%,98%,100%,66%,100%
1,1%,1%,2%,1%,0%,33%,0%

### suggestion_tags_dedicated pedestrian walk signals by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,98%,96%,97%,100%,97%,100%,100%,100%,100%,100%
1,1%,1%,3%,2%,0%,2%,0%,0%,0%,0%,0%

### suggestion_tags_dedicated pedestrian walk signals by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,97%,97%,100%,100%,50%,100%
1,1%,2%,2%,0%,0%,50%,0%

### suggestion_tags_dedicated pedestrian walk signals by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,98%,98%,90%
1,1%,1%,1%,1%,9%

### suggestion_tags_dedicated pedestrian walk signals by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,96%,98%,99%,100%
1,1%,3%,1%,0%,0%

## *Suggestion_Tags_Educate Cyclists* (Each Column Adds Up To 100%):

### suggestion_tags_educate cyclists by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,93%,96%,89%,92%,100%,100%,66%
1,6%,3%,10%,7%,0%,0%,33%

### suggestion_tags_educate cyclists by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,93%,93%,94%,88%,91%,91%,93%,100%,100%,100%,100%
1,6%,6%,5%,11%,8%,8%,6%,0%,0%,0%,0%

### suggestion_tags_educate cyclists by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,93%,97%,88%,100%,100%,100%,100%
1,6%,2%,11%,0%,0%,0%,0%

### suggestion_tags_educate cyclists by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,93%,91%,95%,95%,96%
1,6%,8%,4%,4%,3%

### suggestion_tags_educate cyclists by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,93%,93%,93%,92%,93%
1,6%,6%,6%,7%,6%

## *Suggestion_Tags_Educate Pedestrians* (Each Column Adds Up To 100%):

### suggestion_tags_educate pedestrians by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,98%,97%,98%,100%,100%,100%
1,1%,1%,2%,1%,0%,0%,0%

### suggestion_tags_educate pedestrians by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,100%,97%,98%,94%,100%,100%,100%,100%,100%,100%
1,1%,0%,2%,1%,5%,0%,0%,0%,0%,0%,0%

### suggestion_tags_educate pedestrians by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,99%,97%,100%,100%,100%,100%
1,1%,0%,2%,0%,0%,0%,0%

### suggestion_tags_educate pedestrians by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,98%,97%,100%
1,1%,1%,1%,2%,0%

### suggestion_tags_educate pedestrians by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,98%,98%,97%,97%
1,1%,1%,1%,2%,2%

## *Suggestion_Tags_Enforce Crosswalks* (Each Column Adds Up To 100%):

### suggestion_tags_enforce crosswalks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,95%,98%,100%,100%,66%,100%
1,2%,4%,1%,0%,0%,33%,0%

### suggestion_tags_enforce crosswalks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,96%,98%,94%,100%,100%,100%,90%,100%,100%,100%
1,2%,3%,1%,5%,0%,0%,0%,9%,0%,0%,0%

### suggestion_tags_enforce crosswalks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,95%,97%,75%,100%,50%,100%
1,2%,4%,2%,25%,0%,50%,0%

### suggestion_tags_enforce crosswalks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,97%,96%,97%,100%
1,2%,2%,3%,2%,0%

### suggestion_tags_enforce crosswalks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,97%,97%,97%,97%
1,2%,2%,2%,2%,2%

## *Suggestion_Tags_Enforce Speed* (Each Column Adds Up To 100%):

### suggestion_tags_enforce speed by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,88%,88%,88%,86%,100%,100%,100%
1,11%,11%,11%,13%,0%,0%,0%

### suggestion_tags_enforce speed by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,88%,84%,84%,92%,88%,93%,100%,90%,100%,100%,100%
1,11%,15%,15%,7%,11%,6%,0%,9%,0%,0%,0%

### suggestion_tags_enforce speed by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,88%,88%,89%,50%,100%,100%,100%
1,11%,11%,10%,50%,0%,0%,0%

### suggestion_tags_enforce speed by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,88%,86%,90%,87%,90%
1,11%,13%,9%,12%,9%

### suggestion_tags_enforce speed by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,88%,82%,90%,92%,89%
1,11%,17%,9%,7%,10%

## *Suggestion_Tags_Enforce Trimming Of Bushes* (Each Column Adds Up To 100%):

### suggestion_tags_enforce trimming of bushes by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,98%,99%,97%,100%,100%,100%
1,1%,1%,0%,2%,0%,0%,0%

### suggestion_tags_enforce trimming of bushes by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,98%,97%,98%,100%,100%,100%,100%,100%,90%,100%
1,1%,1%,2%,1%,0%,0%,0%,0%,0%,10%,0%

### suggestion_tags_enforce trimming of bushes by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,99%,99%,100%,100%,100%,100%
1,1%,0%,0%,0%,0%,0%,0%

### suggestion_tags_enforce trimming of bushes by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,98%,100%,100%
1,1%,1%,1%,0%,0%

### suggestion_tags_enforce trimming of bushes by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,97%,97%,100%,100%
1,1%,2%,2%,0%,0%

## *Suggestion_Tags_Improve Route 9 Access* (Each Column Adds Up To 100%):

### suggestion_tags_improve route 9 access by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,97%,97%,100%,100%,100%,100%
1,1%,2%,2%,0%,0%,0%,0%

### suggestion_tags_improve route 9 access by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,98%,96%,100%,95%,100%,100%,100%,90%,100%,100%
1,1%,1%,3%,0%,4%,0%,0%,0%,9%,0%,0%

### suggestion_tags_improve route 9 access by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,95%,100%,100%,100%,100%,100%
1,1%,4%,0%,0%,0%,0%,0%

### suggestion_tags_improve route 9 access by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,97%,97%,96%
1,1%,1%,2%,2%,3%

### suggestion_tags_improve route 9 access by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,98%,97%,97%,100%
1,1%,1%,2%,2%,0%

## *Suggestion_Tags_Maintain Crosswalks* (Each Column Adds Up To 100%):

### suggestion_tags_maintain crosswalks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,95%,97%,99%,100%,100%,100%
1,2%,4%,2%,0%,0%,0%,0%

### suggestion_tags_maintain crosswalks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,94%,97%,97%,98%,97%,100%,100%,100%,100%,100%
1,2%,5%,2%,2%,1%,2%,0%,0%,0%,0%,0%

### suggestion_tags_maintain crosswalks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,95%,96%,100%,100%,100%,100%
1,2%,4%,3%,0%,0%,0%,0%

### suggestion_tags_maintain crosswalks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,97%,98%,94%,93%
1,2%,2%,1%,5%,6%

### suggestion_tags_maintain crosswalks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,96%,97%,96%,100%
1,2%,3%,2%,3%,0%

## *Suggestion_Tags_Maintain Sidewalks* (Each Column Adds Up To 100%):

### suggestion_tags_maintain sidewalks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,88%,88%,85%,91%,100%,100%,100%
1,11%,11%,14%,8%,0%,0%,0%

### suggestion_tags_maintain sidewalks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,88%,85%,83%,89%,98%,83%,100%,90%,90%,100%,100%
1,11%,14%,16%,10%,1%,16%,0%,9%,9%,0%,0%

### suggestion_tags_maintain sidewalks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,88%,91%,82%,100%,66%,100%,100%
1,11%,8%,17%,0%,33%,0%,0%

### suggestion_tags_maintain sidewalks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,88%,87%,93%,88%,90%
1,11%,12%,6%,11%,9%

### suggestion_tags_maintain sidewalks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,88%,83%,89%,94%,95%
1,11%,16%,10%,5%,4%

## *Suggestion_Tags_More Crosswalks* (Each Column Adds Up To 100%):

### suggestion_tags_more crosswalks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,93%,92%,91%,97%,80%,66%,100%
1,6%,7%,8%,2%,20%,33%,0%

### suggestion_tags_more crosswalks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,93%,89%,94%,94%,97%,91%,96%,95%,100%,90%,100%
1,6%,10%,5%,5%,2%,8%,3%,4%,0%,10%,0%

### suggestion_tags_more crosswalks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,93%,90%,93%,100%,100%,100%,100%
1,6%,9%,6%,0%,0%,0%,0%

### suggestion_tags_more crosswalks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,93%,93%,94%,91%,96%
1,6%,6%,5%,8%,3%

### suggestion_tags_more crosswalks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,93%,91%,92%,95%,100%
1,6%,8%,7%,4%,0%

## *Suggestion_Tags_More Sidewalks* (Each Column Adds Up To 100%):

### suggestion_tags_more sidewalks by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,82%,77%,80%,92%,80%,100%,100%
1,17%,22%,19%,7%,20%,0%,0%

### suggestion_tags_more sidewalks by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,82%,80%,82%,85%,88%,85%,83%,76%,72%,70%,100%
1,17%,19%,17%,14%,11%,14%,16%,23%,27%,30%,0%

### suggestion_tags_more sidewalks by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,82%,78%,84%,75%,100%,100%,100%
1,17%,21%,15%,25%,0%,0%,0%

### suggestion_tags_more sidewalks by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,82%,83%,77%,87%,80%
1,17%,16%,22%,12%,19%

### suggestion_tags_more sidewalks by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,82%,78%,80%,87%,93%
1,17%,21%,19%,12%,6%

## *Suggestion_Tags_More Signs* (Each Column Adds Up To 100%):

### suggestion_tags_more signs by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,97%,98%,99%,100%,100%,100%
1,1%,2%,1%,0%,0%,0%,0%

### suggestion_tags_more signs by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,98%,97%,97%,98%,100%,96%,100%,100%,100%,100%
1,1%,1%,2%,2%,1%,0%,3%,0%,0%,0%,0%

### suggestion_tags_more signs by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,97%,97%,100%,100%,100%,100%
1,1%,2%,2%,0%,0%,0%,0%

### suggestion_tags_more signs by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,98%,95%,96%
1,1%,1%,1%,4%,3%

### suggestion_tags_more signs by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,97%,97%,98%,100%
1,1%,2%,2%,1%,0%

## *Suggestion_Tags_More Stop Signs* (Each Column Adds Up To 100%):

### suggestion_tags_more stop signs by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,96%,98%,99%,80%,100%,100%
1,2%,3%,1%,0%,20%,0%,0%

### suggestion_tags_more stop signs by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,94%,100%,98%,97%,100%,100%,100%,100%,100%,100%
1,2%,5%,0%,1%,2%,0%,0%,0%,0%,0%,0%

### suggestion_tags_more stop signs by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,95%,98%,100%,100%,100%,100%
1,2%,4%,1%,0%,0%,0%,0%

### suggestion_tags_more stop signs by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,98%,94%,98%,100%
1,2%,1%,5%,1%,0%

### suggestion_tags_more stop signs by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,96%,98%,97%,100%
1,2%,3%,1%,2%,0%

## *Suggestion_Tags_More Traffic Lights* (Each Column Adds Up To 100%):

### suggestion_tags_more traffic lights by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,98%,97%,97%,80%,100%,100%
1,2%,1%,2%,2%,20%,0%,0%

### suggestion_tags_more traffic lights by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,95%,97%,100%,100%,97%,96%,100%,100%,100%,100%
1,2%,4%,2%,0%,0%,2%,3%,0%,0%,0%,0%

### suggestion_tags_more traffic lights by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,97%,97%,100%,100%,100%,100%
1,2%,2%,2%,0%,0%,0%,0%

### suggestion_tags_more traffic lights by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,98%,97%,97%,96%
1,2%,1%,2%,2%,3%

### suggestion_tags_more traffic lights by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,98%,97%,98%,95%
1,2%,1%,2%,1%,4%

## *Suggestion_Tags_No Bike Lanes* (Each Column Adds Up To 100%):

### suggestion_tags_no bike lanes by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,96%,97%,96%,97%,80%,100%,100%
1,3%,2%,3%,2%,20%,0%,0%

### suggestion_tags_no bike lanes by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,96%,96%,98%,94%,95%,97%,100%,100%,100%,100%,100%
1,3%,3%,1%,5%,4%,2%,0%,0%,0%,0%,0%

### suggestion_tags_no bike lanes by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,96%,96%,96%,100%,100%,100%,100%
1,3%,3%,3%,0%,0%,0%,0%

### suggestion_tags_no bike lanes by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,96%,95%,97%,100%,96%
1,3%,4%,2%,0%,3%

### suggestion_tags_no bike lanes by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,96%,97%,96%,96%,95%
1,3%,2%,3%,3%,4%

## *Suggestion_Tags_Outlaw Cycling* (Each Column Adds Up To 100%):

### suggestion_tags_outlaw cycling by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,99%,97%,98%,100%,100%,100%
1,1%,0%,2%,1%,0%,0%,0%

### suggestion_tags_outlaw cycling by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,99%,97%,98%,98%,97%,100%,100%,100%,100%,100%
1,1%,0%,2%,1%,1%,2%,0%,0%,0%,0%,0%

### suggestion_tags_outlaw cycling by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,100%,98%,100%,100%,100%,100%
1,1%,0%,1%,0%,0%,0%,0%

### suggestion_tags_outlaw cycling by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,99%,100%,100%
1,1%,1%,0%,0%,0%

### suggestion_tags_outlaw cycling by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,97%,100%,100%,93%
1,1%,2%,0%,0%,6%

## *Suggestion_Tags_Parking On One Side Only* (Each Column Adds Up To 100%):

### suggestion_tags_parking on one side only by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,98%,98%,98%,100%,100%,100%
1,1%,1%,1%,1%,0%,0%,0%

### suggestion_tags_parking on one side only by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,98%,98%,100%,100%,97%,100%,100%,100%,100%,100%
1,1%,1%,1%,0%,0%,2%,0%,0%,0%,0%,0%

### suggestion_tags_parking on one side only by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,100%,97%,75%,100%,100%,100%
1,1%,0%,2%,25%,0%,0%,0%

### suggestion_tags_parking on one side only by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,100%,98%,100%
1,1%,1%,0%,1%,0%

### suggestion_tags_parking on one side only by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,97%,99%,99%,100%
1,1%,2%,0%,0%,0%

## *Suggestion_Tags_Reduce On-Street Parking* (Each Column Adds Up To 100%):

### suggestion_tags_reduce on-street parking by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,96%,98%,97%,80%,100%,100%
1,2%,3%,1%,2%,20%,0%,0%

### suggestion_tags_reduce on-street parking by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,96%,98%,100%,98%,95%,100%,100%,100%,100%,100%
1,2%,3%,1%,0%,1%,4%,0%,0%,0%,0%,0%

### suggestion_tags_reduce on-street parking by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,97%,97%,75%,100%,100%,100%
1,2%,2%,2%,25%,0%,0%,0%

### suggestion_tags_reduce on-street parking by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,97%,97%,97%,96%
1,2%,2%,2%,2%,3%

### suggestion_tags_reduce on-street parking by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,95%,98%,97%,100%
1,2%,4%,1%,2%,0%

## *Suggestion_Tags_Reduce Speed* (Each Column Adds Up To 100%):

### suggestion_tags_reduce speed by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,91%,90%,91%,92%,100%,100%,100%
1,8%,9%,8%,7%,0%,0%,0%

### suggestion_tags_reduce speed by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,91%,92%,88%,93%,92%,89%,100%,95%,90%,70%,100%
1,8%,7%,11%,6%,7%,10%,0%,4%,9%,30%,0%

### suggestion_tags_reduce speed by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,91%,92%,91%,75%,66%,50%,50%
1,8%,7%,8%,25%,33%,50%,50%

### suggestion_tags_reduce speed by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,91%,91%,90%,92%,90%
1,8%,8%,9%,7%,9%

### suggestion_tags_reduce speed by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,91%,87%,92%,94%,97%
1,8%,12%,7%,5%,2%

## *Suggestion_Tags_Sidewalk On Mt Airy S* (Each Column Adds Up To 100%):

### suggestion_tags_sidewalk on mt airy s by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,97%,95%,98%,100%,100%,100%,66%
1,2%,4%,1%,0%,0%,0%,33%

### suggestion_tags_sidewalk on mt airy s by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,97%,99%,99%,100%,85%,97%,100%,100%,100%,100%,100%
1,2%,0%,0%,0%,14%,2%,0%,0%,0%,0%,0%

### suggestion_tags_sidewalk on mt airy s by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,97%,96%,99%,100%,100%,100%,100%
1,2%,3%,0%,0%,0%,0%,0%

### suggestion_tags_sidewalk on mt airy s by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,97%,97%,98%,97%,100%
1,2%,2%,1%,2%,0%

### suggestion_tags_sidewalk on mt airy s by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,97%,98%,96%,98%,97%
1,2%,1%,3%,1%,2%

## *Suggestion_Tags_Speed Bumps* (Each Column Adds Up To 100%):

### suggestion_tags_speed bumps by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,95%,93%,96%,97%,100%,100%,100%
1,4%,6%,3%,2%,0%,0%,0%

### suggestion_tags_speed bumps by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,95%,94%,94%,96%,98%,93%,96%,100%,100%,100%,100%
1,4%,5%,5%,3%,1%,6%,3%,0%,0%,0%,0%

### suggestion_tags_speed bumps by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,95%,96%,94%,100%,100%,50%,100%
1,4%,3%,5%,0%,0%,50%,0%

### suggestion_tags_speed bumps by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,95%,96%,94%,95%,96%
1,4%,3%,5%,4%,3%

### suggestion_tags_speed bumps by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,95%,93%,96%,97%,100%
1,4%,6%,3%,2%,0%

## *Suggestion_Tags_Speed Cameras* (Each Column Adds Up To 100%):

### suggestion_tags_speed cameras by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,98%,99%,98%,97%,100%,100%,100%
1,1%,0%,1%,2%,0%,0%,0%

### suggestion_tags_speed cameras by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,98%,98%,97%,100%,100%,97%,100%,100%,100%,100%,100%
1,1%,1%,2%,0%,0%,2%,0%,0%,0%,0%,0%

### suggestion_tags_speed cameras by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,98%,99%,98%,100%,100%,100%,100%
1,1%,0%,1%,0%,0%,0%,0%

### suggestion_tags_speed cameras by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,98%,98%,100%,100%,93%
1,1%,1%,0%,0%,6%

### suggestion_tags_speed cameras by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,98%,98%,97%,100%,100%
1,1%,1%,2%,0%,0%

## *Suggestion_Tags_Speed Indicator Signs* (Each Column Adds Up To 100%):

### suggestion_tags_speed indicator signs by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,99%,98%,99%,100%,100%,100%,100%
1,0%,1%,0%,0%,0%,0%,0%

### suggestion_tags_speed indicator signs by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,99%,98%,100%,97%,98%,100%,100%,100%,100%,100%,100%
1,0%,1%,0%,2%,1%,0%,0%,0%,0%,0%,0%

### suggestion_tags_speed indicator signs by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,99%,97%,100%,100%,100%,100%,100%
1,0%,2%,0%,0%,0%,0%,0%

### suggestion_tags_speed indicator signs by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,99%,98%,100%,98%,100%
1,0%,1%,0%,1%,0%

### suggestion_tags_speed indicator signs by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,99%,98%,99%,98%,100%
1,0%,1%,0%,1%,0%

## *Suggestion_Tags_Traffic Calming* (Each Column Adds Up To 100%):

### suggestion_tags_traffic calming by demographic:

,overall,Adult with school kid,Adult without school kid,Senior,College kid,Middle School kid,High School kid
0,99%,99%,98%,100%,100%,100%,100%
1,0%,0%,1%,0%,0%,0%,0%

### suggestion_tags_traffic calming by neighborhood:

,overall,Harmon,Upper Village,Old Post Road North,Mount Airy,Sunset Park,Albany Post Road,Half Moon Bay,Quaker Ridge,Cortlandt,Ossining
0,99%,99%,99%,100%,100%,97%,100%,95%,100%,90%,100%
1,0%,0%,0%,0%,0%,2%,0%,4%,0%,10%,0%

### suggestion_tags_traffic calming by commuter_type:

,overall,I take the train at Croton Harmon,I drive the entire way,I walk the entire way (weather permitting),I bicycle the entire way (weather permitting),I take a bus the entire way,I take the train at another station
0,99%,98%,100%,100%,100%,100%,50%
1,0%,1%,0%,0%,0%,0%,50%

### suggestion_tags_traffic calming by bike_freq:

,overall,Rarely or never,Once in a while,Once every few days,"Every day, or almost every day"
0,99%,99%,99%,100%,93%
1,0%,0%,0%,0%,6%

### suggestion_tags_traffic calming by walk_freq:

,overall,"Every day, or almost every day",Once every few days,Once in a while,Rarely or never
0,99%,98%,99%,99%,100%
1,0%,1%,0%,0%,0%

## Who rides on the sidewalk?

### Overall

In [8]:
# do people generally bike on the sidewalk?
df['bikes_on_sidewalk'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

                                bikes_on_sidewalk
No - I don't bicycle                          48%
No - I only bicycle on the road               29%
Yes                                           23%

### People who never bike

In [9]:
# do people who never bike claim to ride on the sidewalk?
df2 = df[ df['bike_freq'].isin(['Rarely or never']) ]
df2['bikes_on_sidewalk'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

                                bikes_on_sidewalk
No - I don't bicycle                          81%
No - I only bicycle on the road               12%
Yes                                            7%

### People who bike at least occasionally

In [10]:
# do people who ride a bike occasionally or more ride on the sidewalk?
df2 = df[ df['bike_freq'].isin(['Every day, or almost every day', 'Once every few days', 'Once in a while']) ]
df2['bikes_on_sidewalk'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

                                bikes_on_sidewalk
No - I don't bicycle                           1%
No - I only bicycle on the road               53%
Yes                                           46%

### People who bike a lot

In [11]:
# do people who bike a lot ride on the sidewalk?
df2 = df[ df['bike_freq'].isin(['Every day, or almost every day']) ]
df2['bikes_on_sidewalk'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

                                bikes_on_sidewalk
No - I only bicycle on the road               60%
Yes                                           40%

## Who thinks drivers are safe?

### Overall

In [12]:
# do people generally think drivers are safe?
df['drivers_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    drivers_are_safe
1.0               9%
2.0              29%
3.0              48%
4.0              14%

### People who frequently walk

In [13]:
# do people who walk a lot think drivers are safe?
df2 = df[ df['walk_freq'].isin(['Every day, or almost every day', 'Once every few days']) ]
df2['drivers_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    drivers_are_safe
1.0              10%
2.0              32%
3.0              47%
4.0              10%

### People who infrequently walk

In [14]:
# do people who rarely walk think drivers are safe?
df2 = df[ df['walk_freq'].isin(['Rarely or never', 'Once in a while']) ]
df2['drivers_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    drivers_are_safe
1.0               6%
2.0              24%
3.0              48%
4.0              22%

### People who rarely walk

In [15]:
# do people who never walk think drivers are safe?
df2 = df[ df['walk_freq'].isin(['Rarely or never']) ]
df2['drivers_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    drivers_are_safe
1.0               9%
2.0              19%
3.0              43%
4.0              30%

### People who frequently bike

In [16]:
# do people who bike a lot think drivers are safe?
df2 = df[ df['bike_freq'].isin(['Every day, or almost every day', 'Once every few days']) ]
df2['drivers_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    drivers_are_safe
1.0              12%
2.0              31%
3.0              49%
4.0               8%

### People who infrequently bike

In [17]:
# do people who never bike think drivers are safe?
df2 = df[ df['bike_freq'].isin(['Rarely or never', 'Once in a while']) ]
df2['drivers_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    drivers_are_safe
1.0               8%
2.0              29%
3.0              47%
4.0              16%

### People who rarely bike

In [18]:
# do people who never bike think drivers are safe?
df2 = df[ df['bike_freq'].isin(['Rarely or never']) ]
df2['drivers_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    drivers_are_safe
1.0               6%
2.0              29%
3.0              47%
4.0              18%

## Who thinks bicyclists are safe?

### Overall

In [19]:
# do people generally think bicyclists are safe?
df['bicyclists_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    bicyclists_are_safe
1.0                 13%
2.0                 23%
3.0                 49%
4.0                 16%

### People who frequently bike

In [20]:
# do people who bike a lot think bicyclists are safe
df2 = df[ df['bike_freq'].isin(['Every day, or almost every day', 'Once every few days']) ]
df2['bicyclists_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    bicyclists_are_safe
1.0                  4%
2.0                 14%
3.0                 56%
4.0                 26%

### People who infrequently bike

In [21]:
# do people who never bike think bicyclists are safe
df2 = df[ df['bike_freq'].isin(['Rarely or never', 'Once in a while']) ]
df2['bicyclists_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    bicyclists_are_safe
1.0                 15%
2.0                 25%
3.0                 46%
4.0                 13%

### People who rarely bike

In [22]:
# do people who never bike think bicyclists are safe
df2 = df[ df['bike_freq'].isin(['Rarely or never']) ]
df2['bicyclists_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index()

     bicyclists_are_safe
1.0                   16
2.0                   29
3.0                   44
4.0                   11

### People who frequently walk

In [23]:
# do people who walk a lot think drivers are safe?
df2 = df[ df['walk_freq'].isin(['Every day, or almost every day', 'Once every few days']) ]
df2['bicyclists_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    bicyclists_are_safe
1.0                 11%
2.0                 23%
3.0                 50%
4.0                 16%

### People who infrequently walk

In [24]:
# do people who walk a lot think drivers are safe?
df2 = df[ df['walk_freq'].isin(['Rarely or never', 'Once in a while']) ]
df2['bicyclists_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    bicyclists_are_safe
1.0                 17%
2.0                 23%
3.0                 46%
4.0                 14%

### People who rarely walk

In [25]:
# do people who walk a lot think drivers are safe?
df2 = df[ df['walk_freq'].isin(['Rarely or never']) ]
df2['bicyclists_are_safe'].value_counts().to_frame().apply(lambda x: 100 * x / x.sum()).round(0).astype(int).sort_index().astype(str) + '%'

    bicyclists_are_safe
1.0                 26%
2.0                 19%
3.0                 45%
4.0                 11%