## Import data from CSV data file
The CSV file has been exported from Google Sheets survey responses.

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('responses.csv', index_col=None, parse_dates=['Timestamp'])

## Clean up column names
The original column names are the questions.... let's simplifies them.  And while we're at it, set appropriate columns as categorical data to speed up analysis.

In [2]:
# replace long column titles with shorter versions
df.columns = [ 'date', 'neighborhood', 'demographic', 'schools', 'child_bus_freq', 'child_bike_freq', 'child_driven_freq', 'child_drive_freq', 'child_walk_freq', 'child_drive_reason', 'child_no_walk_reason', 'child_no_bike_reason', 'walk_freq', 'bike_freq', 'bikes_on_sidewalk', 'self_jog_frequency', 'commutes', 'child_self_school', 'child_self_bus_freq', 'child_self_bike_freq', 'child_self_driven_freq', 'child_self_drive_freq', 'child_self_walk_freq', 'child_self_commutes', 'child_self_has_children', 'commuter_distance', 'commuter_type', 'commuter_walk_to_station_freq', 'commuter_bike_to_station_freq', 'commuter_drive_to_station_freq', 'commuter_carpool_to_station_freq', 'commuter_driven_to_station_freq', 'commuter_bus_to_station_freq', 'no_walk_reason', 'no_bike_reason', 'drive_reason', 'feelings', 'problem_areas', 'drivers_are_safe', 'bicyclists_are_safe', 'suggested_improvements', 'additional_comments', 'owns_business', 'business_type', 'business_space', 'business_pedestrian_synergy', 'business_bicyclists_synergy', 'business_bike_rack_interest', 'business_promotion_interest', 'business_additional_comments', 'final_comments', 'contact_interest', 'contact_info', 'wants_pdf' ]
categorical_columns = [ 'neighborhood', 'demographic', 'schools', 'child_bus_freq', 'child_bike_freq', 'child_driven_freq', 'child_drive_freq', 'child_walk_freq', 'child_drive_reason', 'child_no_walk_reason', 'child_no_bike_reason', 'walk_freq', 'bike_freq', 'bikes_on_sidewalk', 'self_jog_frequency', 'commutes', 'child_self_school', 'child_self_bus_freq', 'child_self_bike_freq', 'child_self_driven_freq', 'child_self_drive_freq', 'child_self_walk_freq', 'child_self_commutes', 'child_self_has_children', 'commuter_distance', 'commuter_type', 'commuter_walk_to_station_freq', 'commuter_bike_to_station_freq', 'commuter_drive_to_station_freq', 'commuter_carpool_to_station_freq', 'commuter_driven_to_station_freq', 'commuter_bus_to_station_freq', 'no_walk_reason', 'no_bike_reason', 'drive_reason', 'drivers_are_safe', 'bicyclists_are_safe', 'suggested_improvements', 'owns_business', 'business_type', 'business_space', 'business_pedestrian_synergy', 'business_bicyclists_synergy', 'business_bike_rack_interest', 'business_promotion_interest', 'contact_interest', 'wants_pdf' ]
for col in categorical_columns :
    df[col] = df[col].astype('category')
    continue
    
# show the top few rows
df.head()

,date,neighborhood,demographic,schools,child_bus_freq,child_bike_freq,child_driven_freq,child_drive_freq,child_walk_freq,child_drive_reason,...,business_space,business_pedestrian_synergy,business_bicyclists_synergy,business_bike_rack_interest,business_promotion_interest,business_additional_comments,final_comments,contact_interest,contact_info,wants_pdf
0,2019-02-27 15:32:07,Mount Airy,Adult with school age children living with me,PVC,"Every day, or almost every day",Rarely or never - for other reasons,Once every few days,Rarely or never - my children are too young,Once in a while,The bus schedule does not match our schedule,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,elizamccarthy@gmail.com,No
1,2019-02-27 17:03:24,Harmon,Adult with school age children living with me,Homeschooled,Rarely or never,Rarely or never - for other reasons,Once every few days,Rarely or never - for other reasons,Rarely or never - for other reasons,"Our daughter is homeschooled, but attends alte...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Amos Bloomberg,No
2,2019-02-28 08:41:08,Old Post Road N area,Adult with school age children living with me,PVC,Rarely or never,Once in a while,Once in a while,Rarely or never - my children are too young,"Every day, or almost every day","No - we do not drive, or prefer not to drive",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Matt Arnold,No
3,2019-03-07 10:27:34,Croton Landing,Adult with no school age children living with me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-03-19 20:27:28,Harmon,Adult with school age children living with me,CET,"Every day, or almost every day",Rarely or never - my children are too young,Once in a while,Rarely or never - my children are too young,Rarely or never - my children are too young,Early morning program once a week,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Daniel Castner,Yes

## Clean up neighborhood names
Neighorhood names were verbose in the actual survey... and some respondents wrote their own locations.  We group those respondents into their nearest neighborhoods and use consistent neighborhood names here.

In [3]:
df['neighborhood'] = df['neighborhood'].str.strip() # remove white space
df['neighborhood'] = df['neighborhood'].replace({
    
    # simplifying neighborhood names
    'Albany Post Road / Prickly Pear Hill / Scenic Dr area': 'Albany Post Road', 
    'Cortlandt outside of Croton': 'Cortlandt',
    'Old Post Road N area': 'Old Post Road North',
    'Quaker Ridge / Quaker Bridge area': 'Quaker Ridge',
    'Sunset Park area': 'Sunset Park',
    'Teatown area': 'Teatown',
    'Upper Village (the area nearest the Black Cow coffee shop)': 'Upper Village',

    # lumping CET/library area into Harmon
    'CET': 'Harmon', 
    'By CET': 'Harmon',
    'By the library/cemetery/CET': 'Harmon',
    'End of Cleveland near path': 'Harmon',
    'Cleveland near CET/Library': 'Harmon',
    'Cleveland/Park': 'Harmon',
    'Duck Pond': 'Harmon',
    'Harmon Park': 'Harmon',
    'Irving Ave': 'Harmon',
    'Ridge Rd.': 'Harmon',
    'Truesdale Drive': 'Harmon',
    'along the croton river': 'Harmon',
    'Behind high school': 'Harmon',
    
    # lumping Old Post Road South and Sunset Park together
    'Old Post Road S': 'Sunset Park', 
    
    # lumping North Riverside area into Croton Landing
    'North Riverside': 'Croton Landing',
    'Palmer on High St': 'Croton Landing',
    'lower village': 'Croton Landing',
    'Brook St': 'Croton Landing',
    
    # lumping Old Post Road North and Croton Landing together
    'Croton Landing': 'Old Post Road North', 
    
    # lumping nearby streets into Upper Village
    'Bari Manor': 'Upper Village',
    'Harrison st': 'Upper Village',
    'Wells Ave': 'Upper Village',
    
    # lumping Batten Rd and Crompond Rd areas with Mount Airy
    'Batten Road': 'Mount Airy',
    'The trails': 'Mount Airy',
    '129 near dam': 'Mount Airy', 
    
    #lumping Teatown into Quaker Ridge, since there were few Teatown respondents
    'Teatown': 'Quaker Ridge' 
})

df['neighborhood'].value_counts()

Harmon                 151
Upper Village          107
Old Post Road North     68
Mount Airy              55
Sunset Park             42
Albany Post Road        29
Half Moon Bay           19
Quaker Ridge             9
Cortlandt                8
Ossining                 1
Name: neighborhood, dtype: int64

## Clean up demographics
Some respondents indicated their own demographic titles... we're standardizing these.

In [4]:

df['demographic'] = df['demographic'].str.strip() # remove white space
df['demographic'] = df['demographic'].replace({
    
    # creating new category for adults with small children
    'Adult with a 22 year old and a 3 year old living with me': 'Adult with small child',
    'Adult with an infant': 'Adult with small child',
    'Adult with new baby': 'Adult with small child',
    'Adult with toddler': 'Adult with small child',
    'Adult with toddler living with me': 'Adult with small child',
    'Adult with toddlers living with me': 'Adult with small child',
    'Adult with young children': 'Adult with small child',
    'Adult with young children living with me': 'Adult with small child',
    'Adult with 3year old': 'Adult with small child',
    
    # lump adults with infants & toddlers into adults with no school age children
    'Adult with small child': 'Adult with no school age children living with me',
    'Adult with spouse and adult children living with us.': 'Adult with no school age children living with me',
    
    # lumping adults with college kids into the adults with no school age children category
    'adult with post college child living with me': 'Adult with no school age children living with me',
    'Adult with College Children': 'Adult with no school age children living with me',
    'Adult with College Children': 'Adult with no school age children living with me'

})    

# simplify response text
df['demographic'] = df['demographic'].replace({
    'Adult with school age children living with me': 'Adult with school kid',
    'Adult with no school age children living with me': 'Adult without school kid',
    'College student': 'College kid',
    'High School student': 'High School kid',
    'Middle School student': 'Middle School kid',
})

df['demographic'].value_counts()

Adult with school kid       194
Adult without school kid    165
Senior                      128
College kid                   5
High School kid               3
Middle School kid             1
Name: demographic, dtype: int64

## Save cleaned up data to CSV file
So it can be analyzed in subsequent programs.

In [5]:
df.to_csv('responses_scrubbed.csv', index=False)